<div class="row g-3">
  <div class="col-lg-6">
    <div class="card-panel mb-3"><div class="panel-head"><div><h3>Backups</h3><p>Tenant-scoped compressed JSON backup.</p></div><button class="btn btn-primary ajax-action" data-url="<?= url('/tools/backup') ?>">Run Backup</button></div><?php foreach($backups as $b): ?><div class="report-row"><span><?= e($b['backup_type'].' · '.$b['created_at']) ?><small><?= e($b['file_path']??$b['message']??'') ?></small></span><span class="status-badge <?= $b['status']==='success'?'success':($b['status']==='failed'?'danger':'') ?>"><?= e($b['status']) ?></span></div><?php endforeach; ?></div>
    <div class="card-panel mb-3"><h3 class="h6">API Tokens</h3><form class="ajax-form row g-2 mb-3" method="post" action="<?= url('/tools/api-tokens') ?>"><?= csrf_field() ?><div class="col-md-4"><input class="form-control" name="name" placeholder="Token name"></div><div class="col-md-5"><select class="form-select" name="user_id"><?php foreach($users as $u): ?><option value="<?= $u['id'] ?>"><?= e($u['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-primary w-100">Generate</button></div></form><?php foreach($tokens as $t): ?><div class="report-row"><span><?= e($t['name']) ?><small><?= e($t['user_name'].' · '.($t['last_used_at']??'never used')) ?></small></span><span class="status-badge"><?= $t['revoked_at']?'revoked':'active' ?></span></div><?php endforeach; ?></div>
    <div class="card-panel"><h3 class="h6">Tags</h3><form class="ajax-form d-flex gap-2 mb-3" method="post" action="<?= url('/tools/tags') ?>"><?= csrf_field() ?><input class="form-control" name="name" placeholder="VIP, Contract, Hotel..." required><button class="btn btn-outline-primary">Add</button></form><div class="d-flex gap-2 flex-wrap"><?php foreach($tags as $tag): ?><span class="status-badge"><?= e($tag['name']) ?></span><?php endforeach; ?></div></div>
  </div>
  <div class="col-lg-6">
    <div class="card-panel mb-3"><h3 class="h6">Custom Fields</h3><form class="ajax-form row g-2 mb-3" method="post" action="<?= url('/tools/custom-fields') ?>"><?= csrf_field() ?><div class="col-md-4"><select class="form-select" name="entity_type"><option>customer</option><option>asset</option><option>job</option><option>invoice</option></select></div><div class="col-md-4"><input class="form-control" name="label" placeholder="Label" required></div><div class="col-md-4"><input class="form-control" name="field_key" placeholder="field_key" required></div><div class="col-md-6"><select class="form-select" name="field_type"><option>text</option><option>number</option><option>date</option><option>select</option></select></div><div class="col-md-6"><button class="btn btn-outline-primary w-100">Add Field</button></div></form><?php foreach($customFields as $f): ?><div class="report-row"><span><?= e($f['label']) ?><small><?= e($f['entity_type'].'.'.$f['field_key']) ?></small></span><span class="status-badge"><?= e($f['field_type']) ?></span></div><?php endforeach; ?></div>
    <div class="card-panel"><div class="panel-head"><div><h3>Webhooks</h3><p>HMAC signed, queued delivery with exponential retry.</p></div><button class="btn btn-sm btn-outline-primary ajax-action" data-url="<?= url('/tools/webhooks/deliver') ?>">Deliver Queue</button></div><form class="ajax-form row g-2 mb-3" method="post" action="<?= url('/tools/webhooks') ?>"><?= csrf_field() ?><div class="col-md-4"><input class="form-control" name="name" placeholder="Name"></div><div class="col-md-8"><input class="form-control" name="endpoint_url" placeholder="https://..." required></div><div class="col-12"><input class="form-control" name="events" placeholder="job.created, job.completed, payment.received"></div><div class="col-12"><button class="btn btn-outline-primary">Add Webhook</button></div></form><?php foreach($webhooks as $w): ?><div class="report-row"><span><?= e($w['name']) ?><small><?= e($w['endpoint_url']) ?></small></span><span class="status-badge"><?= $w['active']?'active':'off' ?></span></div><?php endforeach; ?><hr><h4 class="h6">Recent Deliveries</h4><?php foreach($deliveries as $d): ?><div class="report-row"><span><?= e($d['event_name']) ?><small><?= e($d['webhook_name'].' · attempts '.$d['attempts'].' · '.$d['created_at']) ?></small></span><span class="status-badge <?= $d['delivered_at']?'success':(($d['response_code']??0)>=400?'danger':'warning') ?>"><?= $d['delivered_at']?'delivered':($d['response_code']??'queued') ?></span></div><?php endforeach; ?></div>
  </div>
</div>
<div class="card-panel mt-3"><h3 class="h6">Audit Log</h3><div class="table-responsive"><table class="table datatable"><thead><tr><th>Date</th><th>User</th><th>Module</th><th>Action</th><th>Record</th><th>IP</th></tr></thead><tbody><?php foreach($audit as $a): ?><tr><td><?= e($a['created_at']) ?></td><td><?= e($a['user_name']??'System') ?></td><td><?= e($a['module']) ?></td><td><?= e($a['action']) ?></td><td>#<?= e($a['record_id']??'-') ?></td><td><?= e($a['ip_address']??'-') ?></td></tr><?php endforeach; ?></tbody></table></div></div>
