<?php
namespace App\Services;
use App\Core\Database;
final class BackupService {
    private const TABLES=['branches','users','roles','user_roles','customers','customer_contacts','customer_sites','customer_assets','leads','lead_activities','service_categories','services','service_requests','surveys','quotations','quotation_items','jobs','job_technicians','job_status_history','job_work_logs','job_photos','skills','technicians','technician_skills','job_required_skills','warehouses','items','stock_balances','stock_movements','job_materials','stock_transfers','stock_transfer_items','vendors','purchase_requests','purchase_request_items','purchase_orders','purchase_order_items','goods_receipts','goods_receipt_items','invoices','invoice_items','payments','customer_payment_proofs','job_expenses','contracts','contract_assets','maintenance_schedules','warranties','service_reports','documents','comments','notifications','audit_logs','activity_logs','custom_fields','custom_field_values','settings','number_sequences','sla_policies','job_signatures','recurring_jobs','tags','entity_tags','api_tokens','webhooks','webhook_deliveries','customer_portal_users','quotation_approvals','email_templates','backup_logs','tenant_feature_overrides','subscription_payments'];
    public static function tenantJson(int $tenantId,?int $userId):string{
        $db=Database::connection();$dir=BASE_PATH.'/storage/backups/'.$tenantId;if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new \RuntimeException('Cannot create backup directory.');$file=$dir.'/tenant-'.$tenantId.'-'.date('Ymd-His').'.json.gz';$backupId=null;
        try{$db->prepare("INSERT INTO backup_logs(tenant_id,backup_type,status,initiated_by,created_at) VALUES(?,'full','running',?,NOW())")->execute([$tenantId,$userId]);$backupId=(int)$db->lastInsertId();$payload=['generated_at'=>date(DATE_ATOM),'format'=>'servicepro-tenant-backup-v1','tenant_id'=>$tenantId,'tables'=>[]];
            foreach(self::TABLES as $table){$check=$db->query("SHOW TABLES LIKE ".$db->quote($table))->fetchColumn();if(!$check)continue;$s=$db->prepare("SELECT * FROM {$table} WHERE tenant_id=?");$s->execute([$tenantId]);$payload['tables'][$table]=$s->fetchAll();}
            $rp=$db->prepare("SELECT rp.* FROM role_permissions rp JOIN roles r ON r.id=rp.role_id WHERE r.tenant_id=?");$rp->execute([$tenantId]);$payload['tables']['role_permissions']=$rp->fetchAll();
            $sub=$db->prepare("SELECT * FROM subscriptions WHERE tenant_id=?");$sub->execute([$tenantId]);$payload['tables']['subscriptions']=$sub->fetchAll();
            $t=$db->prepare("SELECT * FROM tenants WHERE id=?");$t->execute([$tenantId]);$payload['tenant']=$t->fetch();$raw=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);if($raw===false)throw new \RuntimeException('Unable to encode backup JSON.');$bytes=function_exists('gzencode')?gzencode($raw,6):$raw;if(file_put_contents($file,$bytes)===false)throw new \RuntimeException('Unable to write backup file.');$db->prepare("UPDATE backup_logs SET file_path=?,file_size=?,status='success',completed_at=NOW() WHERE id=?")->execute([str_replace(BASE_PATH.'/','',$file),filesize($file),$backupId]);return $file;
        }catch(\Throwable $e){if($backupId)$db->prepare("UPDATE backup_logs SET status='failed',message=?,completed_at=NOW() WHERE id=?")->execute([$e->getMessage(),$backupId]);throw $e;}
    }
}
