<?php
namespace App\Services;
use App\Core\Database;
final class ScheduledService {
    public static function runTenant(int $tenantId):array{
        $db=Database::connection();$out=['recurring_jobs'=>RecurringService::generateDue($tenantId),'overdue_invoices'=>0,'contract_alerts'=>0,'warranty_alerts'=>0,'low_stock_alerts'=>0];
        $q=$db->prepare("SELECT i.id,i.invoice_number,i.customer_id,i.balance,c.email FROM invoices i JOIN customers c ON c.id=i.customer_id AND c.tenant_id=i.tenant_id WHERE i.tenant_id=? AND i.deleted_at IS NULL AND i.balance>0 AND i.due_date<CURDATE() AND i.status IN('Sent','Partial')");$q->execute([$tenantId]);foreach($q->fetchAll() as $r){$db->prepare("UPDATE invoices SET status='Overdue',updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([$r['id'],$tenantId]);EventService::emit($tenantId,'invoice.overdue',['invoice_number'=>$r['invoice_number'],'balance'=>$r['balance']],null,$r['email']?:null,'invoice_overdue');$out['overdue_invoices']++;}
        $c=$db->prepare("SELECT c.id,c.contract_number,c.end_date,c.customer_id,cu.email FROM contracts c JOIN customers cu ON cu.id=c.customer_id AND cu.tenant_id=c.tenant_id WHERE c.tenant_id=? AND c.deleted_at IS NULL AND c.status='Active' AND c.end_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY) AND NOT EXISTS(SELECT 1 FROM notifications n WHERE n.tenant_id=c.tenant_id AND n.type='contract.expiring' AND JSON_UNQUOTE(JSON_EXTRACT(n.data,'$.contract_id'))=CAST(c.id AS CHAR) AND n.created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY))");$c->execute([$tenantId]);foreach($c->fetchAll() as $r){EventService::emit($tenantId,'contract.expiring',['contract_id'=>$r['id'],'contract_number'=>$r['contract_number'],'end_date'=>$r['end_date']],null,$r['email']?:null,'contract_expiry');$out['contract_alerts']++;}
        $w=$db->prepare("SELECT w.id,w.warranty_end,j.job_number,c.email,ca.asset_code FROM warranties w JOIN jobs j ON j.id=w.job_id AND j.tenant_id=w.tenant_id JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id LEFT JOIN customer_assets ca ON ca.id=j.asset_id AND ca.tenant_id=j.tenant_id WHERE w.tenant_id=? AND w.status='Active' AND w.warranty_end BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY) AND NOT EXISTS(SELECT 1 FROM notifications n WHERE n.tenant_id=w.tenant_id AND n.type='warranty.expiring' AND JSON_UNQUOTE(JSON_EXTRACT(n.data,'$.warranty_id'))=CAST(w.id AS CHAR) AND n.created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY))");$w->execute([$tenantId]);foreach($w->fetchAll() as $r){EventService::emit($tenantId,'warranty.expiring',['warranty_id'=>$r['id'],'job_number'=>$r['job_number'],'asset_code'=>$r['asset_code'],'warranty_end'=>$r['warranty_end']],null,$r['email']?:null,'warranty_expiry');$out['warranty_alerts']++;}
        $ls=$db->prepare("SELECT i.id,i.sku,i.item_name,i.minimum_stock,COALESCE(SUM(sb.quantity),0) qty FROM items i LEFT JOIN stock_balances sb ON sb.item_id=i.id AND sb.tenant_id=i.tenant_id WHERE i.tenant_id=? AND i.deleted_at IS NULL AND i.status='active' GROUP BY i.id HAVING qty<=i.minimum_stock AND NOT EXISTS(SELECT 1 FROM notifications n WHERE n.tenant_id=i.tenant_id AND n.type='inventory.low_stock' AND JSON_UNQUOTE(JSON_EXTRACT(n.data,'$.item_id'))=CAST(i.id AS CHAR) AND n.created_at>=DATE_SUB(NOW(),INTERVAL 1 DAY))");$ls->execute([$tenantId]);foreach($ls->fetchAll() as $r){EventService::emit($tenantId,'inventory.low_stock',['item_id'=>$r['id'],'sku'=>$r['sku'],'item_name'=>$r['item_name'],'quantity'=>$r['qty'],'minimum_stock'=>$r['minimum_stock']]);$out['low_stock_alerts']++;}
        return $out;
    }
}
