<?php
namespace App\Services;
final class SimplePdfService {
    public static function output(string $filename,array $lines,string $title='ServicePro',array $options=[]): never {
        $lines=self::wrap($lines,88);$chunks=array_chunk($lines,42);if(!$chunks)$chunks=[[]];
        $objects=[];$objects[1]='<< /Type /Catalog /Pages 2 0 R >>';$objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';$objects[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';$next=5;
        $images=[];$logo=self::image($options['logo_path']??null);if($logo){$logo['name']='Logo';$images[]=$logo;}
        foreach(($options['attachments']??[]) as $i=>$a){$img=self::image($a['path']??null);if($img){$img['name']='Sig'.($i+1);$img['label']=(string)($a['label']??'Signature');$images[]=$img;}}
        foreach($images as &$img){$img['id']=$next++;$objects[$img['id']]="<< /Type /XObject /Subtype /Image /Width {$img['width']} /Height {$img['height']} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ".strlen($img['data'])." >>\nstream\n".$img['data']."\nendstream";}unset($img);
        $xobj='';foreach($images as $img)$xobj.='/'.$img['name'].' '.$img['id'].' 0 R ';
        $resources='<< /Font << /F1 3 0 R /F2 4 0 R >>'.($xobj?' /XObject << '.$xobj.' >>':'').' >>';
        $pageIds=[];$pageNo=0;$footer=(string)($options['footer']??'');
        foreach($chunks as $chunk){$pageNo++;$pageId=$next++;$contentId=$next++;$pageIds[]=$pageId;$stream=self::content($chunk,$title,$pageNo,$footer,$logo);$objects[$pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources {$resources} /Contents {$contentId} 0 R >>";$objects[$contentId]="<< /Length ".strlen($stream)." >>\nstream\n{$stream}\nendstream";}
        $signatures=array_values(array_filter($images,fn($x)=>str_starts_with($x['name'],'Sig')));if($signatures){foreach(array_chunk($signatures,4) as $sigChunk){$pageNo++;$pageId=$next++;$contentId=$next++;$pageIds[]=$pageId;$stream=self::signatureContent($sigChunk,$title,$pageNo,$footer,$logo);$objects[$pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources {$resources} /Contents {$contentId} 0 R >>";$objects[$contentId]="<< /Length ".strlen($stream)." >>\nstream\n{$stream}\nendstream";}}
        $objects[2]='<< /Type /Pages /Kids ['.implode(' ',array_map(fn($id)=>"{$id} 0 R",$pageIds)).'] /Count '.count($pageIds).' >>';ksort($objects);
        $pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";$offset=[0];foreach($objects as $id=>$obj){$offset[$id]=strlen($pdf);$pdf.="{$id} 0 obj\n{$obj}\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf("%010d 00000 n \n",$offset[$i]??0);$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";
        header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._-]/','_',$filename).'"');header('Content-Length: '.strlen($pdf));header('X-Content-Type-Options: nosniff');echo $pdf;exit;
    }
    private static function content(array $lines,string $title,int $page,string $footer,?array $logo): string {
        $out="q\n";if($logo)$out.="110 0 0 55 435 755 cm /Logo Do\n";$out.="Q\nBT\n/F2 16 Tf\n50 800 Td\n(".self::esc($title).") Tj\n/F1 9 Tf\n0 -18 Td\n(".self::esc('Generated '.date('d M Y H:i')).") Tj\n/F1 10 Tf\n0 -28 Td\n";foreach($lines as $i=>$line){if($i>0)$out.="0 -16 Td\n";$out.="(".self::esc($line).") Tj\n";}$out.="ET\n";return $out.self::footer($footer,$page);
    }
    private static function signatureContent(array $images,string $title,int $page,string $footer,?array $logo): string {
        $out="q\n";if($logo)$out.="110 0 0 55 435 755 cm /Logo Do\n";$out.="Q\nBT\n/F2 16 Tf\n50 800 Td\n(".self::esc($title).") Tj\n0 -34 Td\n/F2 13 Tf\n(Signatures / Approvals) Tj\nET\n";
        $positions=[[50,520],[315,520],[50,250],[315,250]];foreach($images as $i=>$img){[$x,$y]=$positions[$i];$w=200;$h=min(130,max(70,$w*($img['height']/$img['width'])));$out.="BT /F2 10 Tf {$x} ".($y+150)." Td (".self::esc($img['label']??'Signature').") Tj ET\nq {$w} 0 0 {$h} {$x} {$y} cm /{$img['name']} Do Q\n";}return $out.self::footer($footer,$page);
    }
    private static function footer(string $footer,int $page):string{$text=trim($footer)!==''?$footer:'Generated by the service provider';return "BT /F1 8 Tf 50 28 Td (".self::esc($text).") Tj 455 0 Td (Page {$page}) Tj ET\n";}
    private static function image(?string $path):?array{
        if(!$path)return null;$full=str_starts_with($path,'/')?$path:(defined('BASE_PATH')?BASE_PATH.'/'.$path:$path);if(!is_file($full))return null;$info=@getimagesize($full);if(!$info)return null;[$w,$h,$type]=$info;$data=null;if($type===IMAGETYPE_JPEG)$data=@file_get_contents($full);elseif($type===IMAGETYPE_PNG&&extension_loaded('gd')){$im=@imagecreatefrompng($full);if($im){$bg=imagecreatetruecolor(imagesx($im),imagesy($im));$white=imagecolorallocate($bg,255,255,255);imagefill($bg,0,0,$white);imagecopy($bg,$im,0,0,0,0,imagesx($im),imagesy($im));ob_start();imagejpeg($bg,null,88);$data=ob_get_clean();imagedestroy($bg);imagedestroy($im);}}if(!$data)return null;return ['width'=>$w,'height'=>$h,'data'=>$data];
    }
    private static function esc(string $s):string{$s=@iconv('UTF-8','Windows-1252//TRANSLIT',$s)?:$s;$s=str_replace(["\r","\n"],' ',$s);return str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$s);}
    private static function wrap(array $lines,int $width):array{$out=[];foreach($lines as $line){foreach(explode("\n",(string)$line) as $p){$wrapped=wordwrap($p,$width,"\n",true);foreach(explode("\n",$wrapped) as $w)$out[]=$w;}}return $out;}
}
