<?php
namespace App\Services;
final class UploadService {
    private const ALLOWED=['image/jpeg'=>'jpg','image/png'=>'png','application/pdf'=>'pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'=>'xlsx','text/csv'=>'csv'];
    private static function dir(int $tenantId,string $folder): string {$dir=BASE_PATH.'/storage/uploads/'.$tenantId.'/'.trim($folder,'/');if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new \RuntimeException('Cannot create upload directory.');return $dir;}
    public static function store(array $file,int $tenantId,string $folder='documents',int $maxBytes=10485760): string {if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new \RuntimeException('Upload failed.');if(($file['size']??0)>$maxBytes)throw new \RuntimeException('File too large.');if(SubscriptionService::wouldExceedStorage($tenantId,(int)($file['size']??0)))throw new \RuntimeException('Tenant storage limit exceeded.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!isset(self::ALLOWED[$mime]))throw new \RuntimeException('Unsupported file type.');$dir=self::dir($tenantId,$folder);$name=bin2hex(random_bytes(20)).'.'.self::ALLOWED[$mime];$dest=$dir.'/'.$name;if(!move_uploaded_file($file['tmp_name'],$dest))throw new \RuntimeException('Cannot store upload.');if(in_array($mime,['image/jpeg','image/png'],true))self::compressImage($dest,$mime);return 'storage/uploads/'.$tenantId.'/'.trim($folder,'/').'/'.$name;}
    public static function storeDataUrl(string $dataUrl,int $tenantId,string $folder='signatures'): string {if(!preg_match('#^data:image/(png|jpeg);base64,(.+)$#',$dataUrl,$m))throw new \RuntimeException('Invalid signature image.');$bytes=base64_decode($m[2],true);if($bytes===false||strlen($bytes)>3_000_000)throw new \RuntimeException('Invalid or too large image.');if(SubscriptionService::wouldExceedStorage($tenantId,strlen($bytes)))throw new \RuntimeException('Tenant storage limit exceeded.');$ext=$m[1]==='jpeg'?'jpg':'png';$dir=self::dir($tenantId,$folder);$name=bin2hex(random_bytes(20)).'.'.$ext;$dest=$dir.'/'.$name;if(file_put_contents($dest,$bytes)===false)throw new \RuntimeException('Cannot save image.');self::compressImage($dest,$m[1]==='jpeg'?'image/jpeg':'image/png');return 'storage/uploads/'.$tenantId.'/'.trim($folder,'/').'/'.$name;}
    private static function compressImage(string $path,string $mime):void{if(!extension_loaded('gd'))return;try{$img=$mime==='image/jpeg'?@imagecreatefromjpeg($path):@imagecreatefrompng($path);if(!$img)return;$w=imagesx($img);$h=imagesy($img);$max=1920;if(max($w,$h)>$max){$ratio=$max/max($w,$h);$nw=max(1,(int)round($w*$ratio));$nh=max(1,(int)round($h*$ratio));$res=imagecreatetruecolor($nw,$nh);if($mime==='image/png'){imagealphablending($res,false);imagesavealpha($res,true);}imagecopyresampled($res,$img,0,0,0,0,$nw,$nh,$w,$h);imagedestroy($img);$img=$res;}if($mime==='image/jpeg')imagejpeg($img,$path,82);else imagepng($img,$path,6);imagedestroy($img);}catch(\Throwable){}}
}
