<?php if(($mode??'management')==='technician'): ?>
<div class="kpi-grid mb-3"><div class="kpi-card"><span class="kpi-icon"><i class="bi bi-tools"></i></span><div><small>Assigned / Active Jobs</small><strong><?= count($jobs) ?></strong></div></div><div class="kpi-card"><span class="kpi-icon"><i class="bi bi-check2-circle"></i></span><div><small>Completed This Month</small><strong><?= e($completedMonth) ?></strong></div></div></div>
<div class="card-panel"><div class="panel-head"><div><h3>My Jobs</h3><p>Mobile-first field workflow: trip, check-in, work log, photos, materials, completion and signature.</p></div></div><div class="row g-3"><?php foreach($jobs as $j):?><div class="col-md-6 col-xl-4"><a class="text-decoration-none text-reset" href="<?= url('/jobs/'.$j['id']) ?>"><div class="portal-card h-100"><div class="d-flex justify-content-between gap-2"><strong><?= e($j['job_number']) ?></strong><span class="status-badge"><?= e($j['status']) ?></span></div><h3 class="h6 mt-3"><?= e($j['customer_name']) ?></h3><p class="text-secondary mb-2"><?= e(mb_strimwidth($j['description'],0,90,'…')) ?></p><small><?= e($j['scheduled_date']?:'Not scheduled') ?> · <?= e($j['priority']) ?></small><?php if($j['site_name']):?><small class="d-block text-secondary mt-2"><i class="bi bi-geo-alt"></i> <?= e($j['site_name'].' · '.$j['address']) ?></small><?php endif;?></div></a></div><?php endforeach;?><?php if(!$jobs):?><div class="col-12"><div class="empty-state">No assigned active jobs.</div></div><?php endif;?></div></div>
<?php else: ?>
<div class="kpi-grid">
<?php $cards=[['Requests Today',$kpi['requests_today'],'bi-inbox'],['Open Jobs',$kpi['open_jobs'],'bi-tools'],['In Progress',$kpi['in_progress'],'bi-play-circle'],['Completed',$kpi['completed'],'bi-check-circle'],['Overdue Jobs',$kpi['overdue'],'bi-clock-history'],['SLA Breached',$kpi['sla_breached'],'bi-stopwatch'],['Active Technicians',$kpi['active_tech'],'bi-person-gear'],['Pending Quotations',$kpi['pending_quotes'],'bi-file-earmark-text'],['Approved Quotations',$kpi['approved_quotes'],'bi-file-earmark-check'],['Low Stock',$kpi['low_stock'],'bi-exclamation-triangle'],['Outstanding',money($kpi['outstanding']),'bi-receipt'],['Revenue This Month',money($kpi['revenue']),'bi-graph-up-arrow'],['Expenses This Month',money($kpi['expenses']),'bi-cash-stack'],['Gross Profit',money($kpi['gross_profit']),'bi-piggy-bank']]; foreach($cards as $c): ?><div class="kpi-card"><span class="kpi-icon"><i class="bi <?= e($c[2]) ?>"></i></span><div><small><?= e($c[0]) ?></small><strong><?= e($c[1]) ?></strong></div></div><?php endforeach; ?>
</div>
<div class="row g-3 mt-1"><div class="col-xl-7"><div class="card-panel h-100"><div class="panel-head"><div><h3>Revenue Trend</h3><p>Last six months invoiced revenue.</p></div></div><canvas class="report-chart" data-type="line" data-labels='<?= e(json_encode(array_column($monthly,'label'))) ?>' data-values='<?= e(json_encode(array_map('floatval',array_column($monthly,'value')))) ?>'></canvas></div></div><div class="col-xl-5"><div class="card-panel h-100"><div class="panel-head"><div><h3>Job Status</h3><p>Current operational workload.</p></div></div><canvas class="report-chart" data-type="bar" data-labels='<?= e(json_encode(array_column($statuses,'label'))) ?>' data-values='<?= e(json_encode(array_map('intval',array_column($statuses,'value')))) ?>'></canvas></div></div></div>
<div class="row g-3 mt-1"><div class="col-xl-8"><div class="card-panel h-100"><div class="panel-head"><div><h3>Upcoming & Active Jobs</h3><p>Operational queue with current technician assignment.</p></div><a class="btn btn-primary" href="<?= url('/jobs') ?>">Open Jobs</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Job</th><th>Customer</th><th>Technician</th><th>Priority</th><th>Schedule</th><th>Status</th></tr></thead><tbody><?php foreach($jobs as $j): ?><tr><td><a href="<?= url('/jobs/'.$j['id']) ?>"><strong><?= e($j['job_number']) ?></strong></a><small class="d-block text-secondary"><?= e($j['service_category']??'Service') ?></small></td><td><?= e($j['customer_name']) ?></td><td><?= e($j['technicians']?:'Unassigned') ?></td><td><?= e($j['priority']) ?></td><td><?= e($j['scheduled_date'] ?: 'Not scheduled') ?></td><td><span class="status-badge"><?= e($j['status']) ?></span></td></tr><?php endforeach; if(!$jobs): ?><tr><td colspan="6" class="text-center text-secondary py-5">No jobs yet.</td></tr><?php endif; ?></tbody></table></div></div></div><div class="col-xl-4"><div class="card-panel mb-3"><h3 class="h6">Low Stock</h3><?php foreach($lowStock as $r):?><div class="report-row"><span><?= e($r['item_name']) ?><small>Minimum <?= e($r['minimum_stock'].' '.$r['unit']) ?></small></span><span class="status-badge danger"><?= e($r['stock'].' '.$r['unit']) ?></span></div><?php endforeach;?><?php if(!$lowStock):?><p class="text-secondary small mb-0">Stock level is healthy.</p><?php endif;?></div><div class="card-panel"><h3 class="h6">Expiring in 30 Days</h3><?php foreach($expiring as $r):?><div class="report-row"><span><?= e($r['reference']) ?><small><?= e($r['kind']) ?></small></span><strong><?= e($r['expiry']) ?></strong></div><?php endforeach;?><?php if(!$expiring):?><p class="text-secondary small mb-0">No contract or warranty nearing expiry.</p><?php endif;?></div></div></div>
<?php endif; ?>
