<?php
use App\Controllers\{AuthController,PasswordController,AccountController,DashboardController,CustomerController,ServiceRequestController,SurveyController,QuotationController,JobController,DispatchController,ItemController,PurchaseController,InvoiceController,ModuleController,LeadController,SettingsController,UserController,ReportController,NotificationController,PortalController,PortalAdminController,PlatformController,PrintController,MediaController,SearchController,ApiController,AdminToolsController,ImportController,MaintenanceController,AssetController,MetadataController,TechnicianController,CollaborationController,BarcodeController,ContractAssetController};
use App\Middleware\{AuthMiddleware,TenantMiddleware,PlatformAdminMiddleware};

$router->get('/',function(){\App\Core\Response::redirect(\App\Core\Auth::check()?(\App\Core\Auth::isPlatformAdmin()?'/platform':'/dashboard'):'/login');});
$router->get('/login',[AuthController::class,'showLogin']);$router->post('/login',[AuthController::class,'login']);$router->get('/forgot-password',[PasswordController::class,'forgotForm']);$router->post('/forgot-password',[PasswordController::class,'forgot']);$router->get('/reset-password',[PasswordController::class,'resetForm']);$router->post('/reset-password',[PasswordController::class,'reset']);$router->post('/logout',[AuthController::class,'logout'],[AuthMiddleware::class]);

// Public customer portal (uses its own customer session and tenant lookup).
$router->get('/a/{token}',[AssetController::class,'publicDetail']);
$router->get('/portal/login',[PortalController::class,'loginForm']);$router->post('/portal/login',[PortalController::class,'login']);$router->post('/portal/logout',[PortalController::class,'logout']);$router->get('/portal',[PortalController::class,'dashboard']);$router->post('/portal/requests',[PortalController::class,'request']);$router->post('/portal/quotations/{id}/approve',[PortalController::class,'approve']);$router->post('/portal/invoices/{id}/payment-proof',[PortalController::class,'paymentProof']);$router->get('/portal/quotation/{id}',[PortalController::class,'quotationPdf']);$router->get('/portal/invoice/{id}',[PortalController::class,'invoicePdf']);$router->get('/portal/service-report/{id}',[PortalController::class,'reportPdf']);

$tenantMw=[AuthMiddleware::class,TenantMiddleware::class];
$router->get('/dashboard',[DashboardController::class,'index'],$tenantMw);
$router->get('/profile',[AccountController::class,'index'],$tenantMw);$router->post('/profile',[AccountController::class,'save'],$tenantMw);$router->post('/profile/password',[AccountController::class,'password'],$tenantMw);$router->post('/profile/sessions/revoke-all',[AccountController::class,'revokeAll'],$tenantMw);$router->post('/profile/sessions/{id}/revoke',[AccountController::class,'revoke'],$tenantMw);
$router->get('/search',[SearchController::class,'index'],$tenantMw);

$router->get('/leads',[LeadController::class,'index'],$tenantMw);$router->post('/leads',[LeadController::class,'create'],$tenantMw);$router->post('/leads/{id}/status',[LeadController::class,'status'],$tenantMw);
$router->get('/customers',[CustomerController::class,'index'],$tenantMw);$router->post('/customers',[CustomerController::class,'store'],$tenantMw);$router->get('/customers/{id}',[CustomerController::class,'show'],$tenantMw);$router->post('/customers/{id}/contacts',[CustomerController::class,'contact'],$tenantMw);
$router->post('/leads/{id}/convert',[LeadController::class,'convert'],$tenantMw);
$router->get('/assets/{id}/qr',[AssetController::class,'qr'],$tenantMw);
$router->get('/metadata/{entity}/{id}',[MetadataController::class,'get'],$tenantMw);$router->post('/metadata/{entity}/{id}',[MetadataController::class,'save'],$tenantMw);
$router->get('/collab/{entity}/{id}',[CollaborationController::class,'data'],$tenantMw);$router->post('/collab/{entity}/{id}/comments',[CollaborationController::class,'comment'],$tenantMw);$router->post('/collab/{entity}/{id}/documents',[CollaborationController::class,'document'],$tenantMw);$router->get('/documents/{id}/download',[CollaborationController::class,'download'],$tenantMw);
$router->get('/technicians/{id}/skills',[TechnicianController::class,'skills'],$tenantMw);$router->post('/technicians/{id}/skills',[TechnicianController::class,'setSkills'],$tenantMw);$router->post('/jobs/{id}/required-skills',[TechnicianController::class,'setJobSkills'],$tenantMw);$router->get('/jobs/{id}/recommendations',[TechnicianController::class,'recommend'],$tenantMw);

$router->get('/service-requests',[ServiceRequestController::class,'index'],$tenantMw);$router->post('/service-requests',[ServiceRequestController::class,'store'],$tenantMw);$router->post('/service-requests/{id}/status',[ServiceRequestController::class,'status'],$tenantMw);$router->post('/service-requests/{id}/convert/{target}',[ServiceRequestController::class,'convert'],$tenantMw);
$router->get('/surveys',[SurveyController::class,'index'],$tenantMw);$router->post('/surveys',[SurveyController::class,'store'],$tenantMw);$router->post('/surveys/{id}/convert',[SurveyController::class,'convert'],$tenantMw);
$router->get('/quotations',[QuotationController::class,'index'],$tenantMw);$router->post('/quotations',[QuotationController::class,'store'],$tenantMw);$router->get('/quotations/{id}',[QuotationController::class,'show'],$tenantMw);$router->post('/quotations/{id}/status',[QuotationController::class,'status'],$tenantMw);$router->post('/quotations/{id}/approve',[QuotationController::class,'approve'],$tenantMw);$router->post('/quotations/{id}/convert',[QuotationController::class,'convert'],$tenantMw);

$router->get('/jobs',[JobController::class,'index'],$tenantMw);$router->post('/jobs',[JobController::class,'store'],$tenantMw);$router->get('/jobs/{id}',[JobController::class,'show'],$tenantMw);$router->post('/jobs/{id}/assign',[JobController::class,'assign'],$tenantMw);$router->post('/jobs/{id}/unassign',[JobController::class,'unassign'],$tenantMw);$router->post('/jobs/{id}/status',[JobController::class,'status'],$tenantMw);$router->post('/jobs/{id}/checkin',[JobController::class,'checkin'],$tenantMw);$router->post('/jobs/{id}/worklog',[JobController::class,'worklog'],$tenantMw);$router->post('/jobs/{id}/photo',[JobController::class,'photo'],$tenantMw);$router->post('/jobs/{id}/material',[JobController::class,'material'],$tenantMw);$router->post('/jobs/{id}/expense',[JobController::class,'expense'],$tenantMw);$router->post('/jobs/{id}/signature',[JobController::class,'signature'],$tenantMw);$router->post('/jobs/{id}/invoice',[JobController::class,'invoice'],$tenantMw);$router->post('/jobs/{id}/warranty',[JobController::class,'warranty'],$tenantMw);
$router->get('/contracts/{id}/assets',[ContractAssetController::class,'index'],$tenantMw);$router->post('/contracts/{id}/assets',[ContractAssetController::class,'save'],$tenantMw);
$router->get('/dispatch',[DispatchController::class,'index'],$tenantMw);$router->post('/dispatch/{id}/schedule',[DispatchController::class,'schedule'],$tenantMw);$router->get('/calendar/events',[DispatchController::class,'events'],$tenantMw);

$router->get('/inventory',[ItemController::class,'index'],$tenantMw);$router->get('/inventory/{id}/barcode',[BarcodeController::class,'item'],$tenantMw);$router->post('/inventory',[ItemController::class,'store'],$tenantMw);$router->post('/inventory/adjust',[ItemController::class,'adjust'],$tenantMw);$router->post('/inventory/transfer',[ItemController::class,'transfer'],$tenantMw);
$router->get('/purchasing',[PurchaseController::class,'index'],$tenantMw);$router->post('/purchasing/requests',[PurchaseController::class,'request'],$tenantMw);$router->post('/purchasing/requests/{id}/approve',[PurchaseController::class,'approve'],$tenantMw);$router->post('/purchasing/orders',[PurchaseController::class,'order'],$tenantMw);$router->post('/purchasing/orders/{id}/receive',[PurchaseController::class,'receive'],$tenantMw);

$router->get('/invoices',[InvoiceController::class,'index'],$tenantMw);$router->post('/invoices',[InvoiceController::class,'store'],$tenantMw);$router->get('/invoices/{id}',[InvoiceController::class,'show'],$tenantMw);$router->post('/invoices/{id}/payment',[InvoiceController::class,'payment'],$tenantMw);$router->post('/invoices/{id}/status',[InvoiceController::class,'status'],$tenantMw);$router->post('/payment-proofs/{id}/review',[InvoiceController::class,'reviewProof'],$tenantMw);

$router->get('/reports',[ReportController::class,'index'],$tenantMw);$router->get('/reports/export/jobs',[ReportController::class,'exportJobs'],$tenantMw);$router->get('/reports/export/jobs.xls',[ReportController::class,'exportJobsExcel'],$tenantMw);$router->get('/reports/export/summary.pdf',[ReportController::class,'exportSummaryPdf'],$tenantMw);
$router->get('/notifications',[NotificationController::class,'index'],$tenantMw);$router->post('/notifications/{id}/read',[NotificationController::class,'read'],$tenantMw);
$router->get('/settings',[SettingsController::class,'index'],$tenantMw);$router->post('/settings',[SettingsController::class,'save'],$tenantMw);$router->post('/settings/branding',[SettingsController::class,'branding'],$tenantMw);
$router->get('/users',[UserController::class,'index'],$tenantMw);$router->post('/users',[UserController::class,'create'],$tenantMw);$router->post('/users/{id}/role',[UserController::class,'assign'],$tenantMw);$router->post('/users/{id}/reset-password',[UserController::class,'reset'],$tenantMw);$router->post('/roles',[UserController::class,'role'],$tenantMw);
$router->get('/portal-users',[PortalAdminController::class,'index'],$tenantMw);$router->post('/portal-users',[PortalAdminController::class,'create'],$tenantMw);
$router->get('/tools',[AdminToolsController::class,'index'],$tenantMw);$router->post('/tools/custom-fields',[AdminToolsController::class,'customField'],$tenantMw);$router->post('/tools/api-tokens',[AdminToolsController::class,'apiToken'],$tenantMw);$router->post('/tools/webhooks',[AdminToolsController::class,'webhook'],$tenantMw);$router->post('/tools/backup',[AdminToolsController::class,'backup'],$tenantMw);$router->post('/tools/tags',[AdminToolsController::class,'tag'],$tenantMw);$router->post('/tools/email-templates',[AdminToolsController::class,'emailTemplate'],$tenantMw);$router->post('/tools/webhooks/deliver',[AdminToolsController::class,'deliverWebhooks'],$tenantMw);
$router->get('/import',[ImportController::class,'index'],$tenantMw);$router->get('/import/template/{type}',[ImportController::class,'template'],$tenantMw);$router->post('/import/preview',[ImportController::class,'preview'],$tenantMw);$router->post('/import/commit',[ImportController::class,'commit'],$tenantMw);
$router->post('/maintenance/run',[MaintenanceController::class,'run'],$tenantMw);

// Config-driven CRUD modules: leads, sites, assets, catalog, technicians, warehouses, vendors, contracts, PM, warranty, recurring jobs, branches, SLA.
$router->get('/manage/{module}',[ModuleController::class,'index'],$tenantMw);$router->post('/manage/{module}',[ModuleController::class,'save'],$tenantMw);$router->post('/manage/{module}/{id}/delete',[ModuleController::class,'delete'],$tenantMw);

// Tenant protected generated documents / media.
$router->get('/print/invoice/{id}',[PrintController::class,'invoice'],$tenantMw);$router->get('/print/quotation/{id}',[PrintController::class,'quotation'],$tenantMw);$router->get('/print/service-report/{id}',[PrintController::class,'serviceReport'],$tenantMw);$router->get('/job-photos/{id}',[MediaController::class,'jobPhoto'],$tenantMw);$router->get('/job-signatures/{id}',[MediaController::class,'signature'],$tenantMw);

// REST API v1 uses Bearer token auth inside ApiController rather than browser session.
$router->get('/api/v1/{resource}',[ApiController::class,'resource']);

// Platform super admin.
$platformMw=[AuthMiddleware::class,PlatformAdminMiddleware::class];$router->get('/platform',[PlatformController::class,'index'],$platformMw);$router->post('/platform/tenants',[PlatformController::class,'create'],$platformMw);$router->post('/platform/tenants/{id}/status',[PlatformController::class,'status'],$platformMw);$router->post('/platform/tenants/{id}/subscription',[PlatformController::class,'subscription'],$platformMw);$router->post('/platform/tenants/{id}/delete',[PlatformController::class,'delete'],$platformMw);$router->post('/platform/tenants/{id}/reset-admin',[PlatformController::class,'resetAdmin'],$platformMw);$router->post('/platform/tenants/{id}/feature',[PlatformController::class,'feature'],$platformMw);$router->post('/platform/tenants/{id}/payment',[PlatformController::class,'payment'],$platformMw);$router->post('/platform/backup',[PlatformController::class,'globalBackup'],$platformMw);
