<div class="page-actions"><div><p class="mb-0">Master data <?= e($cfg['title']) ?>. Semua data otomatis dibatasi ke tenant aktif.</p></div><div class="d-flex gap-2"><?php if(in_array($module,['maintenance','recurring-jobs'],true)): ?><button class="btn btn-outline-primary ajax-action" data-url="<?= url('/maintenance/run') ?>"><i class="bi bi-arrow-repeat"></i> Generate Due Jobs</button><?php endif; ?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#moduleModal" data-module-new="1"><i class="bi bi-plus-lg"></i> Add <?= e(rtrim($cfg['title'],'s')) ?></button></div></div>
<div class="card-panel"><div class="table-responsive"><table class="table align-middle datatable"><thead><tr><?php foreach($cfg['list'] as $label): ?><th><?= e($label) ?></th><?php endforeach; ?><th class="text-end">Action</th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr><?php foreach($cfg['list'] as $key=>$label): ?><td><?php $v=$row[$key]??''; if(str_contains(strtolower($key),'price')||in_array($key,['value','estimated_value'],true)) echo e(money((float)$v)); elseif(in_array($key,['active','taxable'],true)) echo $v?'<span class="status-badge success">Yes</span>':'<span class="status-badge">No</span>'; elseif($key==='status') echo '<span class="status-badge">'.e($v).'</span>'; else echo e((string)$v); ?></td><?php endforeach; ?><td class="text-end"><?php if($module==='leads' && ($row['status']??'')!=='Won'): ?><button class="btn btn-sm btn-outline-success ajax-action" data-url="<?= url('/leads/'.$row['id'].'/convert') ?>" title="Convert to Customer"><i class="bi bi-person-check"></i></button> <?php endif; ?><?php if($module==='contracts'): ?><a class="btn btn-sm btn-outline-primary" href="<?= url('/contracts/'.$row['id'].'/assets') ?>" title="Covered Assets"><i class="bi bi-boxes"></i></a> <?php endif; ?><?php if($module==='technicians'): ?><button class="btn btn-sm btn-outline-primary tech-skills-btn" data-id="<?= $row['id'] ?>" title="Skills"><i class="bi bi-patch-check"></i></button> <?php endif; ?><?php if($module==='customer-assets'): ?><a class="btn btn-sm btn-outline-primary" href="<?= url('/assets/'.$row['id'].'/qr') ?>" title="Asset QR"><i class="bi bi-qr-code"></i></a> <button class="btn btn-sm btn-light metadata-btn" data-entity="asset" data-id="<?= $row['id'] ?>" title="Custom fields & tags"><i class="bi bi-tags"></i></button> <?php endif; ?><button class="btn btn-sm btn-light module-edit" data-record="<?= e(base64_encode(json_encode($row,JSON_UNESCAPED_UNICODE))) ?>"><i class="bi bi-pencil"></i></button><?php if($cfg['soft_delete']??false): ?> <button class="btn btn-sm btn-light text-danger module-delete" data-url="<?= url('/manage/'.$module.'/'.$row['id'].'/delete') ?>"><i class="bi bi-trash"></i></button><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></div>
<div class="modal fade" id="moduleModal"><div class="modal-dialog modal-lg"><form class="modal-content ajax-form" method="post" action="<?= url('/manage/'.$module) ?>"><?= csrf_field() ?><input type="hidden" name="id" value=""><div class="modal-header"><h5><?= e($cfg['title']) ?></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<?php foreach($cfg['fields'] as $f): $type=$f['type']??'text'; ?><div class="<?= $type==='textarea'?'col-12':'col-md-6' ?>"><label class="form-label"><?= e($f['label']) ?><?= ($f['required']??false)?' *':'' ?></label>
<?php if($type==='textarea'): ?><textarea class="form-control" rows="3" name="<?= e($f['name']) ?>" <?= ($f['required']??false)?'required':'' ?>></textarea>
<?php elseif($type==='select'): ?><select class="form-select" name="<?= e($f['name']) ?>" <?= ($f['required']??false)?'required':'' ?>><option value="">Select</option><?php foreach($f['options'] as $k=>$v): $value=is_int($k)?$v:$k; ?><option value="<?= e($value) ?>"><?= e($v) ?></option><?php endforeach; ?></select>
<?php elseif($type==='select_sql'): ?><select class="form-select" name="<?= e($f['name']) ?>" <?= ($f['required']??false)?'required':'' ?>><option value="">Select</option><?php foreach($options[$f['name']]??[] as $o): ?><option value="<?= (int)$o['id'] ?>"><?= e($o['label']) ?></option><?php endforeach; ?></select>
<?php else: ?><input class="form-control" type="<?= e($type) ?>" name="<?= e($f['name']) ?>" <?= isset($f['step'])?'step="'.e($f['step']).'"':'' ?> <?= isset($f['placeholder'])?'placeholder="'.e($f['placeholder']).'"':'' ?> <?= ($f['required']??false)?'required':'' ?>><?php endif; ?>
<div class="invalid-feedback"></div></div><?php endforeach; ?></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save</button></div></form></div></div>

<?php if($module==='technicians'): ?><div class="modal fade" id="techSkillsModal"><div class="modal-dialog"><form class="modal-content ajax-form" id="techSkillsForm" method="post"><?= csrf_field() ?><div class="modal-header"><h5 id="techSkillsTitle">Technician Skills</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="techSkillsBody"></div><div class="modal-footer"><button class="btn btn-primary">Save Skills</button></div></form></div></div><?php endif; ?>
