<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response,Session};
use App\Services\{UploadService,AuditService};
final class AccountController extends Controller {
    public function index():void{$db=Database::connection();$id=Auth::id();$s=$db->prepare("SELECT id,name,email,phone,photo,language,theme,last_login_at,created_at FROM users WHERE id=? LIMIT 1");$s->execute([$id]);$profile=$s->fetch();$x=$db->prepare("SELECT id,session_hash,ip_address,user_agent,last_seen_at,created_at FROM user_sessions WHERE user_id=? AND revoked_at IS NULL ORDER BY last_seen_at DESC");$x->execute([$id]);$this->view('account/index',['title'=>'My Profile','profile'=>$profile,'sessions'=>$x->fetchAll(),'currentSession'=>hash('sha256',session_id())]);}
    public function save():void{$this->requireCsrf();$name=trim((string)Request::input('name'));$phone=trim((string)Request::input('phone'));$language=(string)Request::input('language','id');$theme=(string)Request::input('theme','system');if($name==='')Response::json(['success'=>false,'message'=>'Name wajib diisi.','errors'=>[]],422);if(!in_array($theme,['light','dark','system'],true))$theme='system';if(!in_array($language,['id','en'],true))$language='id';$db=Database::connection();$photo=null;if(isset($_FILES['photo'])&&($_FILES['photo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)$photo=UploadService::store($_FILES['photo'],(int)Auth::tenantId(),'profiles',4*1024*1024);$sql="UPDATE users SET name=?,phone=?,language=?,theme=?,updated_at=NOW()";$args=[$name,$phone?:null,$language,$theme];if($photo){$sql.=',photo=?';$args[]=$photo;}$sql.=' WHERE id=?';$args[]=Auth::id();$db->prepare($sql)->execute($args);$u=Auth::user();$u['name']=$name;$u['photo']=$photo?:($u['photo']??null);$u['language']=$language;$u['theme']=$theme;Session::put('user',$u);AuditService::log('edit','profile',Auth::id(),null,['name'=>$name,'language'=>$language,'theme'=>$theme]);Response::json(['success'=>true,'message'=>'Profile updated.','data'=>['reload'=>true]]);}
    public function password():void{$this->requireCsrf();$current=(string)Request::input('current_password');$password=(string)Request::input('password');$confirm=(string)Request::input('password_confirmation');$db=Database::connection();$s=$db->prepare("SELECT password_hash FROM users WHERE id=?");$s->execute([Auth::id()]);$hash=(string)$s->fetchColumn();if(!password_verify($current,$hash))Response::json(['success'=>false,'message'=>'Current password salah.','errors'=>[]],422);if(strlen($password)<8||$password!==$confirm)Response::json(['success'=>false,'message'=>'New password minimal 8 karakter dan konfirmasi harus sama.','errors'=>[]],422);$db->prepare("UPDATE users SET password_hash=?,updated_at=NOW() WHERE id=?")->execute([password_hash($password,PASSWORD_DEFAULT),Auth::id()]);AuditService::log('password_change','profile',Auth::id());Response::json(['success'=>true,'message'=>'Password changed.','data'=>['reload'=>true]]);}
    public function revoke(string $id):void{$this->requireCsrf();$db=Database::connection();$s=$db->prepare("SELECT session_hash FROM user_sessions WHERE id=? AND user_id=? AND revoked_at IS NULL");$s->execute([(int)$id,Auth::id()]);$h=$s->fetchColumn();if($h)$db->prepare("UPDATE user_sessions SET revoked_at=NOW() WHERE id=? AND user_id=?")->execute([(int)$id,Auth::id()]);if($h===hash('sha256',session_id())){$_SESSION=[];session_destroy();Response::json(['success'=>true,'message'=>'Current session logged out.','redirect'=>url('/login')]);}Response::json(['success'=>true,'message'=>'Session revoked.','data'=>['reload'=>true]]);}
    public function revokeAll():void{$this->requireCsrf();Database::connection()->prepare("UPDATE user_sessions SET revoked_at=NOW() WHERE user_id=? AND session_hash<>? AND revoked_at IS NULL")->execute([Auth::id(),hash('sha256',session_id())]);Response::json(['success'=>true,'message'=>'Other sessions logged out.','data'=>['reload'=>true]]);}
}
