<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{BackupService,WebhookService};
final class AdminToolsController extends Controller {
    public function index():void{if(!Auth::can('settings.manage')&&!Auth::can('audit.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$audit=$db->prepare("SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.tenant_id=? ORDER BY a.id DESC LIMIT 150");$audit->execute([$t]);$cf=$db->prepare("SELECT * FROM custom_fields WHERE tenant_id=? ORDER BY entity_type,label");$cf->execute([$t]);$api=$db->prepare("SELECT a.*,u.name user_name FROM api_tokens a JOIN users u ON u.id=a.user_id WHERE a.tenant_id=? ORDER BY a.id DESC");$api->execute([$t]);$wh=$db->prepare("SELECT * FROM webhooks WHERE tenant_id=? ORDER BY id DESC");$wh->execute([$t]);$bk=$db->prepare("SELECT * FROM backup_logs WHERE tenant_id=? ORDER BY id DESC LIMIT 30");$bk->execute([$t]);$users=$db->prepare("SELECT id,name,email FROM users WHERE tenant_id=? AND deleted_at IS NULL ORDER BY name");$users->execute([$t]);$tags=$db->prepare("SELECT * FROM tags WHERE tenant_id=? ORDER BY name");$tags->execute([$t]);$deliveries=$db->prepare("SELECT d.*,w.name webhook_name FROM webhook_deliveries d JOIN webhooks w ON w.id=d.webhook_id AND w.tenant_id=d.tenant_id WHERE d.tenant_id=? ORDER BY d.id DESC LIMIT 50");$deliveries->execute([$t]);$this->view('tools/index',['title'=>'System Tools','audit'=>$audit->fetchAll(),'customFields'=>$cf->fetchAll(),'tokens'=>$api->fetchAll(),'webhooks'=>$wh->fetchAll(),'backups'=>$bk->fetchAll(),'users'=>$users->fetchAll(),'tags'=>$tags->fetchAll(),'deliveries'=>$deliveries->fetchAll()]);}
    public function customField():void{$this->requireCsrf();if(!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$entity=trim((string)Request::input('entity_type'));$key=preg_replace('/[^a-z0-9_]/','_',strtolower(trim((string)Request::input('field_key'))));$label=trim((string)Request::input('label'));if(!$entity||!$key||!$label)Response::json(['success'=>false,'message'=>'Entity, key, label wajib.','errors'=>[]],422);Database::connection()->prepare("INSERT INTO custom_fields(tenant_id,entity_type,field_key,label,field_type,options,required,created_at) VALUES(?,?,?,?,?,?,?,NOW())")->execute([Auth::tenantId(),$entity,$key,$label,Request::input('field_type','text'),Request::input('options')?:null,(int)(bool)Request::input('required')]);Response::json(['success'=>true,'message'=>'Custom field created.','data'=>['reload'=>true]]);}
    public function apiToken():void{$this->requireCsrf();if(!Auth::can('api.manage')&&!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$user=(int)Request::input('user_id',Auth::id());$name=trim((string)Request::input('name','API Token'));$raw='sp_'.bin2hex(random_bytes(24));Database::connection()->prepare("INSERT INTO api_tokens(tenant_id,user_id,name,token_hash,scopes,expires_at,created_at) VALUES(?,?,?,?,?,?,NOW())")->execute([Auth::tenantId(),$user,$name,hash('sha256',$raw),json_encode(['read']),Request::input('expires_at')?:null]);Response::json(['success'=>true,'message'=>'Token created. Copy it now: '.$raw,'data'=>['token'=>$raw]]);}
    public function webhook():void{$this->requireCsrf();if(!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$url=trim((string)Request::input('endpoint_url'));if(!filter_var($url,FILTER_VALIDATE_URL))Response::json(['success'=>false,'message'=>'Webhook URL invalid.','errors'=>[]],422);$events=array_values(array_filter(array_map('trim',explode(',',(string)Request::input('events')))));Database::connection()->prepare("INSERT INTO webhooks(tenant_id,name,endpoint_url,secret,events,active,created_at,updated_at) VALUES(?,?,?,?,?,1,NOW(),NOW())")->execute([Auth::tenantId(),Request::input('name','Webhook'),$url,bin2hex(random_bytes(24)),json_encode($events)]);Response::json(['success'=>true,'message'=>'Webhook configured.','data'=>['reload'=>true]]);}
    public function backup():void{$this->requireCsrf();if(!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);try{$file=BackupService::tenantJson((int)Auth::tenantId(),Auth::id());}catch(\Throwable $e){Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],500);}Response::json(['success'=>true,'message'=>'Backup completed: '.basename($file),'data'=>['reload'=>true]]);}
    public function tag():void{$this->requireCsrf();if(!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$name=trim((string)Request::input('name'));if($name==='')Response::json(['success'=>false,'message'=>'Tag name required'],422);Database::connection()->prepare("INSERT INTO tags(tenant_id,name,created_at) VALUES(?,?,NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name)")->execute([Auth::tenantId(),$name]);Response::json(['success'=>true,'message'=>'Tag saved.','data'=>['reload'=>true]]);}
    public function emailTemplate():void{$this->requireCsrf();if(!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$key=preg_replace('/[^a-z0-9_]/','_',strtolower(trim((string)Request::input('template_key'))));$subject=trim((string)Request::input('subject'));$body=(string)Request::input('body_html');if(!$key||!$subject||!$body)Response::json(['success'=>false,'message'=>'Template key, subject and body are required'],422);Database::connection()->prepare("INSERT INTO email_templates(tenant_id,template_key,subject,body_html,active,created_at,updated_at) VALUES(?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE subject=VALUES(subject),body_html=VALUES(body_html),active=VALUES(active),updated_at=NOW()")->execute([Auth::tenantId(),$key,$subject,$body,(int)(bool)Request::input('active',1)]);Response::json(['success'=>true,'message'=>'Email template saved.','data'=>['reload'=>true]]);}
    public function deliverWebhooks():void{$this->requireCsrf();if(!Auth::can('settings.manage'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$r=WebhookService::deliverDue((int)Auth::tenantId(),50);Response::json(['success'=>true,'message'=>"Webhook delivery: {$r['delivered']} delivered, {$r['failed']} failed.",'data'=>['reload'=>true]]);}
    private function forbidden():void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
