<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{UploadService,ActivityService,NotificationService};
final class CollaborationController extends Controller {
    private const ENTITIES=['job'=>'job.view','customer'=>'customer.view','asset'=>'asset.view','invoice'=>'invoice.view','quotation'=>'quotation.view','contract'=>'contract.view','service_request'=>'request.view','survey'=>'survey.view'];
    private function allowed(string $entity): bool { return isset(self::ENTITIES[$entity]) && Auth::can(self::ENTITIES[$entity]); }
    private function exists(string $entity,int $id): bool {
        $tables=['job'=>'jobs','customer'=>'customers','asset'=>'customer_assets','invoice'=>'invoices','quotation'=>'quotations','contract'=>'contracts','service_request'=>'service_requests','survey'=>'surveys'];
        $db=Database::connection();$s=$db->prepare("SELECT id FROM {$tables[$entity]} WHERE id=? AND tenant_id=?".(in_array($entity,['job','customer','asset','invoice','quotation','contract'],true)?" AND deleted_at IS NULL":""));$s->execute([$id,Auth::tenantId()]);return (bool)$s->fetchColumn();
    }
    public function data(string $entity,string $id): void {
        if(!$this->allowed($entity)||!$this->exists($entity,(int)$id))Response::json(['success'=>false,'message'=>'Not found or forbidden.','errors'=>[]],404);
        $db=Database::connection();$c=$db->prepare("SELECT c.id,c.body,c.created_at,u.name user_name FROM comments c JOIN users u ON u.id=c.user_id WHERE c.tenant_id=? AND c.entity_type=? AND c.entity_id=? ORDER BY c.id DESC LIMIT 100");$c->execute([Auth::tenantId(),$entity,(int)$id]);$d=$db->prepare("SELECT id,category,file_name,mime_type,file_size,created_at FROM documents WHERE tenant_id=? AND entity_type=? AND entity_id=? ORDER BY id DESC");$d->execute([Auth::tenantId(),$entity,(int)$id]);Response::json(['success'=>true,'message'=>'OK','data'=>['comments'=>$c->fetchAll(),'documents'=>$d->fetchAll()]]);
    }
    public function comment(string $entity,string $id): void {
        $this->requireCsrf();if(!$this->allowed($entity)||!$this->exists($entity,(int)$id))Response::json(['success'=>false,'message'=>'Not found or forbidden.','errors'=>[]],404);$body=trim((string)Request::input('body'));if($body==='')Response::json(['success'=>false,'message'=>'Comment is required.','errors'=>[]],422);$db=Database::connection();$db->prepare("INSERT INTO comments(tenant_id,entity_type,entity_id,user_id,body,created_at) VALUES(?,?,?,?,?,NOW())")->execute([Auth::tenantId(),$entity,(int)$id,Auth::id(),$body]);ActivityService::log($entity,(int)$id,'comment.added',$body);if(preg_match_all('/@([A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,})/i',$body,$m)){foreach(array_unique($m[1]) as $email){$q=$db->prepare("SELECT id FROM users WHERE tenant_id=? AND LOWER(email)=LOWER(?) AND status='active' AND deleted_at IS NULL LIMIT 1");$q->execute([Auth::tenantId(),$email]);if($uid=$q->fetchColumn())NotificationService::internal(Auth::tenantId(),(int)$uid,'mention','You were mentioned',Auth::user()['name'].' mentioned you in '.$entity.' #'.$id,['entity'=>$entity,'entity_id'=>(int)$id]);}}Response::json(['success'=>true,'message'=>'Comment added.','data'=>['reload_collaboration'=>true]]);
    }
    public function document(string $entity,string $id): void {
        $this->requireCsrf();if(!$this->allowed($entity)||!$this->exists($entity,(int)$id))Response::json(['success'=>false,'message'=>'Not found or forbidden.','errors'=>[]],404);if(empty($_FILES['file']))Response::json(['success'=>false,'message'=>'Choose a file.','errors'=>[]],422);try{$path=UploadService::store($_FILES['file'],(int)Auth::tenantId(),'documents/'.$entity);$mime=(new \finfo(FILEINFO_MIME_TYPE))->file(BASE_PATH.'/'.$path);$db=Database::connection();$db->prepare("INSERT INTO documents(tenant_id,entity_type,entity_id,category,file_name,file_path,mime_type,file_size,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,NOW())")->execute([Auth::tenantId(),$entity,(int)$id,Request::input('category','Other'),basename((string)($_FILES['file']['name']??'document')),$path,$mime,(int)($_FILES['file']['size']??0),Auth::id()]);$doc=(int)$db->lastInsertId();ActivityService::log($entity,(int)$id,'document.uploaded',(string)Request::input('category','Other'));Response::json(['success'=>true,'message'=>'Document uploaded.','data'=>['document_id'=>$doc,'reload_collaboration'=>true]]);}catch(\Throwable $e){Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}
    }
    public function download(string $id): never {
        $db=Database::connection();$s=$db->prepare("SELECT * FROM documents WHERE id=? AND tenant_id=?");$s->execute([(int)$id,Auth::tenantId()]);$d=$s->fetch();if(!$d||!$this->allowed($d['entity_type'])||!$this->exists($d['entity_type'],(int)$d['entity_id'])){http_response_code(404);exit;}$base=realpath(BASE_PATH.'/storage/uploads/'.Auth::tenantId());$file=realpath(BASE_PATH.'/'.$d['file_path']);if(!$base||!$file||!str_starts_with($file,$base)||!is_file($file)){http_response_code(404);exit;}header('Content-Type: '.($d['mime_type']?:'application/octet-stream'));header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._ -]/','_',basename($d['file_name'])).'"');header('Content-Length: '.filesize($file));readfile($file);exit;
    }
}
