<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{ActivityService,EventService};
final class DispatchController extends Controller {
    public function index(): void {
        if(!Auth::can('dispatch.view')&&!Auth::can('job.assign')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$tech=$db->prepare("SELECT t.*,u.name,u.phone,b.name branch_name,(SELECT COUNT(*) FROM job_technicians jt JOIN jobs j ON j.id=jt.job_id AND j.tenant_id=jt.tenant_id WHERE jt.tenant_id=t.tenant_id AND jt.user_id=t.user_id AND j.status NOT IN('Completed','Closed','Cancelled')) active_jobs FROM technicians t JOIN users u ON u.id=t.user_id AND u.tenant_id=t.tenant_id LEFT JOIN branches b ON b.id=t.branch_id AND b.tenant_id=t.tenant_id WHERE t.tenant_id=? ORDER BY (t.status='Available') DESC,u.name");$tech->execute([$t]);$jobs=$db->prepare("SELECT j.id,j.job_number,j.customer_id,j.description,j.priority,j.scheduled_date,j.estimated_duration,j.status,c.name customer_name,GROUP_CONCAT(u.name SEPARATOR ', ') technician_names FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id LEFT JOIN job_technicians jt ON jt.job_id=j.id AND jt.tenant_id=j.tenant_id LEFT JOIN users u ON u.id=jt.user_id WHERE j.tenant_id=? AND j.deleted_at IS NULL AND j.status NOT IN('Completed','Closed','Cancelled') GROUP BY j.id ORDER BY j.scheduled_date IS NULL,j.scheduled_date ASC");$jobs->execute([$t]);$this->view('dispatch/index',['title'=>'Dispatch Board','technicians'=>$tech->fetchAll(),'jobs'=>$jobs->fetchAll()]);
    }
    public function schedule(string $id): void {$this->requireCsrf();if(!Auth::can('dispatch.manage')&&!Auth::can('job.assign'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$when=(string)Request::input('scheduled_date');if(!$when)Response::json(['success'=>false,'message'=>'Schedule date wajib diisi.','errors'=>[]],422);$db=Database::connection();$t=Auth::tenantId();$db->prepare("UPDATE jobs SET scheduled_date=?,status=IF(status='Draft','Scheduled',status),updated_by=?,updated_at=NOW() WHERE id=? AND tenant_id=? AND deleted_at IS NULL")->execute([$when,Auth::id(),(int)$id,$t]);$ev=$db->prepare("SELECT j.job_number,c.email FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id WHERE j.id=? AND j.tenant_id=?");$ev->execute([(int)$id,$t]);$er=$ev->fetch();ActivityService::log('job',(int)$id,'scheduled','Job schedule updated',['scheduled_date'=>$when]);EventService::emit((int)$t,'job.scheduled',['job_number'=>$er['job_number']??('JOB#'.$id),'job_id'=>(int)$id,'scheduled_date'=>$when],null,$er['email']??null,'job_scheduled');Response::json(['success'=>true,'message'=>'Schedule diperbarui.','data'=>['reload'=>true]]);}
    public function events(): void {if(!Auth::can('job.view'))Response::json([],403);$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT j.id,j.job_number,j.scheduled_date,j.estimated_duration,j.status,c.name customer_name FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id WHERE j.tenant_id=? AND j.deleted_at IS NULL AND j.scheduled_date IS NOT NULL");$s->execute([$t]);$out=[];foreach($s->fetchAll() as $r){$start=str_replace(' ','T',$r['scheduled_date']);$end=$r['estimated_duration']?date('Y-m-d\TH:i:s',strtotime($r['scheduled_date'].' +'.(int)$r['estimated_duration'].' minutes')):null;$out[]=['id'=>$r['id'],'title'=>$r['job_number'].' · '.$r['customer_name'],'start'=>$start,'end'=>$end,'url'=>url('/jobs/'.$r['id']),'extendedProps'=>['status'=>$r['status']]];}Response::json($out);}
    private function forbidden(): void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
