<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response,Session};
use App\Services\NumberService;
final class ImportController extends Controller {
    public function index():void{if(!Auth::can('settings.manage')&&!Auth::can('customer.create')&&!Auth::can('inventory.manage')){$this->forbidden();return;}$preview=Session::get('_import_preview');$this->view('import/index',['title'=>'Import Data','preview'=>$preview]);}
    public function template(string $type):never{$defs=['customers'=>['name','customer_type','company','phone','whatsapp','email','billing_address','service_address','tax_id','notes'],'items'=>['sku','item_name','category','brand','unit','purchase_price','selling_price','minimum_stock','barcode','location'],'assets'=>['customer_code','category','brand','model','serial_number','installation_date','warranty_start','warranty_end','status']];if(!isset($defs[$type])){http_response_code(404);exit;}header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="servicepro-'.$type.'-template.csv"');$o=fopen('php://output','w');fputcsv($o,$defs[$type]);fclose($o);exit;}
    public function preview():void{$this->requireCsrf();$type=(string)Request::input('type');if(!in_array($type,['customers','items','assets'],true)||!isset($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK){Session::flash('error','Pilih tipe dan file CSV yang valid.');Response::redirect('/import');}$f=fopen($_FILES['file']['tmp_name'],'r');$headers=fgetcsv($f);$rows=[];$errors=[];$line=1;while(($r=fgetcsv($f))!==false&&count($rows)<1000){$line++;if(count($r)!==count($headers)){$errors[]="Line {$line}: jumlah kolom tidak sesuai.";continue;}$row=array_combine($headers,$r);$row['_line']=$line;$rows[]=$row;}fclose($f);Session::put('_import_preview',['type'=>$type,'headers'=>$headers,'rows'=>$rows,'errors'=>$errors]);Response::redirect('/import');}
    public function commit():void{$this->requireCsrf();$p=Session::get('_import_preview');if(!$p||!$p['rows'])Response::json(['success'=>false,'message'=>'Tidak ada preview import.','errors'=>[]],422);$db=Database::connection();$t=(int)Auth::tenantId();$count=0;$db->beginTransaction();try{foreach($p['rows'] as $r){unset($r['_line']);if($p['type']==='customers'){$name=trim((string)($r['name']??''));if($name==='')continue;$num=NumberService::next($t,'customer','CUS');$db->prepare("INSERT INTO customers(tenant_id,customer_code,customer_type,name,company,phone,whatsapp,email,billing_address,service_address,tax_id,notes,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'active',?,NOW(),NOW())")->execute([$t,$num,in_array(($r['customer_type']??''),['Individual','Company'],true)?$r['customer_type']:'Company',$name,$r['company']??null,$r['phone']??null,$r['whatsapp']??null,$r['email']??null,$r['billing_address']??null,$r['service_address']??null,$r['tax_id']??null,$r['notes']??null,Auth::id()]);$count++;}elseif($p['type']==='items'){$name=trim((string)($r['item_name']??''));if($name==='')continue;$sku=trim((string)($r['sku']??''))?:'SKU-'.strtoupper(bin2hex(random_bytes(3)));$db->prepare("INSERT INTO items(tenant_id,sku,item_name,category,brand,unit,purchase_price,selling_price,minimum_stock,barcode,location,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'active',?,NOW(),NOW())")->execute([$t,$sku,$name,$r['category']??null,$r['brand']??null,$r['unit']??'pcs',(float)($r['purchase_price']??0),(float)($r['selling_price']??0),(float)($r['minimum_stock']??0),$r['barcode']??null,$r['location']??null,Auth::id()]);$count++;}elseif($p['type']==='assets'){$cc=trim((string)($r['customer_code']??''));$c=$db->prepare("SELECT id FROM customers WHERE tenant_id=? AND customer_code=? AND deleted_at IS NULL");$c->execute([$t,$cc]);$cid=$c->fetchColumn();if(!$cid)continue;$num=NumberService::next($t,'asset','AST');$db->prepare("INSERT INTO customer_assets(tenant_id,customer_id,asset_code,category,brand,model,serial_number,installation_date,warranty_start,warranty_end,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$t,$cid,$num,$r['category']??null,$r['brand']??null,$r['model']??null,$r['serial_number']??null,$r['installation_date']?:null,$r['warranty_start']?:null,$r['warranty_end']?:null,$r['status']?:'active']);$count++;}}$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();Response::json(['success'=>false,'message'=>'Import failed: '.$e->getMessage(),'errors'=>[]],422);}Session::forget('_import_preview');Response::json(['success'=>true,'message'=>"{$count} record(s) imported.",'data'=>['redirect'=>url('/import')]]);}
    private function forbidden():void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
