<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{AuditService,InventoryService,NumberService,ActivityService};
final class ItemController extends Controller {
    public function index(): void {
        if(!Auth::can('inventory.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT i.*,COALESCE(SUM(sb.quantity),0) stock FROM items i LEFT JOIN stock_balances sb ON sb.item_id=i.id AND sb.tenant_id=i.tenant_id WHERE i.tenant_id=? AND i.deleted_at IS NULL GROUP BY i.id ORDER BY i.item_name");$s->execute([$t]);$b=$db->prepare("SELECT sb.*,i.sku,i.item_name,i.unit,i.minimum_stock,w.name warehouse_name FROM stock_balances sb JOIN items i ON i.id=sb.item_id AND i.tenant_id=sb.tenant_id JOIN warehouses w ON w.id=sb.warehouse_id AND w.tenant_id=sb.tenant_id WHERE sb.tenant_id=? ORDER BY w.name,i.item_name");$b->execute([$t]);$w=$db->prepare("SELECT id,name FROM warehouses WHERE tenant_id=? AND deleted_at IS NULL AND status='active' ORDER BY name");$w->execute([$t]);$m=$db->prepare("SELECT sm.*,i.sku,i.item_name,w.name warehouse_name,u.name user_name FROM stock_movements sm JOIN items i ON i.id=sm.item_id AND i.tenant_id=sm.tenant_id JOIN warehouses w ON w.id=sm.warehouse_id AND w.tenant_id=sm.tenant_id LEFT JOIN users u ON u.id=sm.created_by WHERE sm.tenant_id=? ORDER BY sm.id DESC LIMIT 100");$m->execute([$t]);$this->view('items/index',['title'=>'Inventory','items'=>$s->fetchAll(),'balances'=>$b->fetchAll(),'warehouses'=>$w->fetchAll(),'movements'=>$m->fetchAll()]);
    }
    public function store(): void {$this->requireCsrf();if(!Auth::can('inventory.manage')&&!Auth::can('inventory.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$name=trim((string)Request::input('item_name'));if($name==='')Response::json(['success'=>false,'message'=>'Item name wajib diisi.','errors'=>[]],422);$db=Database::connection();$sku=trim((string)Request::input('sku'))?:'SKU-'.strtoupper(bin2hex(random_bytes(3)));$db->prepare("INSERT INTO items(tenant_id,sku,item_name,category,brand,unit,purchase_price,selling_price,minimum_stock,barcode,location,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'active',?,NOW(),NOW())")->execute([Auth::tenantId(),$sku,$name,Request::input('category'),Request::input('brand'),Request::input('unit','pcs'),(float)Request::input('purchase_price',0),(float)Request::input('selling_price',0),(float)Request::input('minimum_stock',0),Request::input('barcode'),Request::input('location'),Auth::id()]);$id=(int)$db->lastInsertId();AuditService::log('create','item',$id,null,['item_name'=>$name]);Response::json(['success'=>true,'message'=>'Item berhasil dibuat.','data'=>['reload'=>true]]);}
    public function adjust(): void {$this->requireCsrf();if(!Auth::can('inventory.adjust')&&!Auth::can('inventory.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);try{InventoryService::adjust((int)Auth::tenantId(),(int)Request::input('warehouse_id'),(int)Request::input('item_id'),(float)Request::input('quantity'),Auth::id(),(string)Request::input('notes','Stock adjustment'));}catch(\Throwable $e){Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}Response::json(['success'=>true,'message'=>'Stock berhasil disesuaikan.','data'=>['reload'=>true]]);}
    public function transfer(): void {$this->requireCsrf();if(!Auth::can('inventory.transfer')&&!Auth::can('inventory.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$t=(int)Auth::tenantId();$from=(int)Request::input('from_warehouse_id');$to=(int)Request::input('to_warehouse_id');$item=(int)Request::input('item_id');$qty=(float)Request::input('quantity');$db=Database::connection();$num=NumberService::next($t,'stock_transfer','TRF');$db->beginTransaction();try{$db->prepare("INSERT INTO stock_transfers(tenant_id,transfer_number,from_warehouse_id,to_warehouse_id,status,created_by,created_at,updated_at) VALUES(?,?,?,?,'Received',?,NOW(),NOW())")->execute([$t,$num,$from,$to,Auth::id()]);$transferId=(int)$db->lastInsertId();$db->prepare("INSERT INTO stock_transfer_items(tenant_id,stock_transfer_id,item_id,quantity,created_at) VALUES(?,?,?,?,NOW())")->execute([$t,$transferId,$item,$qty]);InventoryService::transfer($t,$from,$to,$item,$qty,$transferId,Auth::id());$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}Response::json(['success'=>true,'message'=>'Stock transfer '.$num.' selesai.','data'=>['reload'=>true]]);}
    private function forbidden(): void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
