<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{AuditService,NumberService,ActivityService,InventoryService,UploadService,EventService};
final class JobController extends Controller {
    private array $statuses=['Draft','Scheduled','Assigned','On The Way','Arrived','In Progress','On Hold','Completed','Customer Confirmation','Closed','Cancelled'];
    public function index(): void {
        if(!Auth::can('job.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$isField=!Auth::can('job.assign')&&$this->isTechnician($db,$t,Auth::id());$filter=$isField?' AND EXISTS(SELECT 1 FROM job_technicians jtx WHERE jtx.tenant_id=j.tenant_id AND jtx.job_id=j.id AND jtx.user_id=?)':'';$sql="SELECT j.*,c.name customer_name,GROUP_CONCAT(DISTINCT u.name SEPARATOR ', ') technicians FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id LEFT JOIN job_technicians jt ON jt.job_id=j.id AND jt.tenant_id=j.tenant_id LEFT JOIN users u ON u.id=jt.user_id AND u.tenant_id=j.tenant_id WHERE j.tenant_id=? AND j.deleted_at IS NULL {$filter} GROUP BY j.id ORDER BY j.scheduled_date IS NULL,j.scheduled_date DESC,j.id DESC";$s=$db->prepare($sql);$args=[$t];if($isField)$args[]=Auth::id();$s->execute($args);$c=$db->prepare("SELECT id,name FROM customers WHERE tenant_id=? AND deleted_at IS NULL ORDER BY name");$c->execute([$t]);$this->view('jobs/index',['title'=>$isField?'My Jobs':'Job Orders','jobs'=>$s->fetchAll(),'customers'=>$c->fetchAll(),'fieldMode'=>$isField]);
    }
    public function show(string $id): void {
        $db=Database::connection();$t=Auth::tenantId();$j=$db->prepare("SELECT j.*,c.name customer_name,creator.branch_id job_branch_id,c.phone customer_phone,c.service_address,c.email customer_email,cs.site_name,cs.address site_address,cs.latitude site_latitude,cs.longitude site_longitude,ca.asset_code,ca.category asset_category,q.quotation_number,sr.request_number FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id LEFT JOIN customer_sites cs ON cs.id=j.site_id AND cs.tenant_id=j.tenant_id LEFT JOIN customer_assets ca ON ca.id=j.asset_id AND ca.tenant_id=j.tenant_id LEFT JOIN quotations q ON q.id=j.quotation_id AND q.tenant_id=j.tenant_id LEFT JOIN service_requests sr ON sr.id=j.service_request_id AND sr.tenant_id=j.tenant_id LEFT JOIN users creator ON creator.id=j.created_by AND creator.tenant_id=j.tenant_id WHERE j.id=? AND j.tenant_id=? AND j.deleted_at IS NULL");$j->execute([(int)$id,$t]);$job=$j->fetch();if(!$job){http_response_code(404);require BASE_PATH.'/app/Views/errors/404.php';return;}if(!$this->canViewJob($db,$job)){$this->forbidden();return;}
        $tech=$db->prepare("SELECT u.id,u.name,u.phone,t.status,t.certification FROM job_technicians jt JOIN users u ON u.id=jt.user_id AND u.tenant_id=jt.tenant_id LEFT JOIN technicians t ON t.user_id=u.id AND t.tenant_id=u.tenant_id WHERE jt.job_id=? AND jt.tenant_id=?");$tech->execute([(int)$id,$t]);
        $available=$db->prepare("SELECT u.id,u.name,t.status,t.certification FROM technicians t JOIN users u ON u.id=t.user_id AND u.tenant_id=t.tenant_id WHERE t.tenant_id=? AND u.deleted_at IS NULL ORDER BY (t.status='Available') DESC,u.name");$available->execute([$t]);
        $logs=$db->prepare("SELECT l.*,u.name technician_name FROM job_work_logs l LEFT JOIN users u ON u.id=l.technician_id WHERE l.job_id=? AND l.tenant_id=? ORDER BY l.id DESC");$logs->execute([(int)$id,$t]);
        $photos=$db->prepare("SELECT p.*,u.name technician_name FROM job_photos p LEFT JOIN users u ON u.id=p.technician_id WHERE p.job_id=? AND p.tenant_id=? ORDER BY p.id DESC");$photos->execute([(int)$id,$t]);
        $materials=$db->prepare("SELECT jm.*,i.item_name,i.sku,i.unit,w.name warehouse_name FROM job_materials jm JOIN items i ON i.id=jm.item_id AND i.tenant_id=jm.tenant_id JOIN warehouses w ON w.id=jm.warehouse_id AND w.tenant_id=jm.tenant_id WHERE jm.job_id=? AND jm.tenant_id=? ORDER BY jm.id DESC");$materials->execute([(int)$id,$t]);
        $expenses=$db->prepare("SELECT e.*,u.name user_name FROM job_expenses e LEFT JOIN users u ON u.id=e.user_id WHERE e.job_id=? AND e.tenant_id=? ORDER BY e.id DESC");$expenses->execute([(int)$id,$t]);
        $sign=$db->prepare("SELECT * FROM job_signatures WHERE job_id=? AND tenant_id=? ORDER BY id DESC");$sign->execute([(int)$id,$t]);
        $items=$db->prepare("SELECT i.id,i.sku,i.item_name,i.unit,i.purchase_price,w.id warehouse_id,w.name warehouse_name,COALESCE(sb.quantity,0) stock FROM items i JOIN stock_balances sb ON sb.item_id=i.id AND sb.tenant_id=i.tenant_id JOIN warehouses w ON w.id=sb.warehouse_id AND w.tenant_id=sb.tenant_id WHERE i.tenant_id=? AND i.deleted_at IS NULL AND sb.quantity>0 ORDER BY i.item_name,w.name");$items->execute([$t]);
        $activity=$db->prepare("SELECT a.*,u.name user_name FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.tenant_id=? AND a.entity_type='job' AND a.entity_id=? ORDER BY a.id DESC LIMIT 50");$activity->execute([$t,(int)$id]);
        $cost=$db->prepare("SELECT (SELECT COALESCE(SUM(quantity*unit_cost),0) FROM job_materials WHERE tenant_id=? AND job_id=?) material_cost,(SELECT COALESCE(SUM(amount),0) FROM job_expenses WHERE tenant_id=? AND job_id=?) expense_cost,(SELECT COALESCE(MAX(q.grand_total),0) FROM quotations q JOIN jobs jj ON jj.quotation_id=q.id AND jj.tenant_id=q.tenant_id WHERE jj.id=? AND jj.tenant_id=?) revenue");$cost->execute([$t,(int)$id,$t,(int)$id,(int)$id,$t]);
        $skills=$db->prepare("SELECT id,name FROM skills WHERE tenant_id=? ORDER BY name");$skills->execute([$t]);
        $req=$db->prepare("SELECT skill_id FROM job_required_skills WHERE tenant_id=? AND job_id=?");$req->execute([$t,(int)$id]);$requiredSkillIds=array_map('intval',$req->fetchAll(\PDO::FETCH_COLUMN));
        $rec=$db->prepare("SELECT t.id technician_id,u.id user_id,u.name,t.status,b.name branch_name,COUNT(DISTINCT ts.skill_id) matched_skills,(SELECT COUNT(*) FROM job_required_skills rr WHERE rr.tenant_id=t.tenant_id AND rr.job_id=?) required_skills,(SELECT COUNT(*) FROM job_technicians jt2 JOIN jobs j2 ON j2.id=jt2.job_id AND j2.tenant_id=jt2.tenant_id WHERE jt2.tenant_id=t.tenant_id AND jt2.user_id=t.user_id AND j2.status NOT IN('Completed','Closed','Cancelled')) workload,COALESCE(AVG(ts.level),0) skill_level FROM technicians t JOIN users u ON u.id=t.user_id AND u.tenant_id=t.tenant_id LEFT JOIN branches b ON b.id=t.branch_id AND b.tenant_id=t.tenant_id LEFT JOIN technician_skills ts ON ts.tenant_id=t.tenant_id AND ts.technician_id=t.id AND ts.skill_id IN(SELECT skill_id FROM job_required_skills WHERE tenant_id=t.tenant_id AND job_id=?) WHERE t.tenant_id=? AND u.deleted_at IS NULL AND u.status='active' GROUP BY t.id,u.id,u.name,t.status,b.name,t.branch_id ORDER BY matched_skills DESC,(t.branch_id <=> ?) DESC,(t.status='Available') DESC,workload ASC,skill_level DESC LIMIT 5");$rec->execute([(int)$id,(int)$id,$t,$job['job_branch_id']??null]);
        $this->view('jobs/show',['title'=>$job['job_number'],'job'=>$job,'technicians'=>$tech->fetchAll(),'availableTechs'=>$available->fetchAll(),'logs'=>$logs->fetchAll(),'photos'=>$photos->fetchAll(),'materials'=>$materials->fetchAll(),'expenses'=>$expenses->fetchAll(),'signatures'=>$sign->fetchAll(),'stockItems'=>$items->fetchAll(),'activity'=>$activity->fetchAll(),'cost'=>$cost->fetch(),'statuses'=>$this->statuses,'skills'=>$skills->fetchAll(),'requiredSkillIds'=>$requiredSkillIds,'recommendations'=>$rec->fetchAll()]);
    }
    public function store(): void {
        $this->requireCsrf();if(!Auth::can('job.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$t=Auth::tenantId();$customer=(int)Request::input('customer_id');$description=trim((string)Request::input('description'));if(!$customer||$description==='')Response::json(['success'=>false,'message'=>'Customer dan deskripsi wajib diisi.','errors'=>[]],422);$db=Database::connection();$num=NumberService::next($t,'job','JOB');$db->prepare("INSERT INTO jobs(tenant_id,job_number,customer_id,site_id,asset_id,service_category,description,priority,scheduled_date,estimated_duration,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'Draft',?,NOW(),NOW())")->execute([$t,$num,$customer,Request::input('site_id')?:null,Request::input('asset_id')?:null,Request::input('service_category'),$description,Request::input('priority','Normal'),Request::input('scheduled_date')?:null,Request::input('estimated_duration')?:null,Auth::id()]);$id=(int)$db->lastInsertId();AuditService::log('create','job',$id,null,['job_number'=>$num]);ActivityService::log('job',$id,'created','Job created');Response::json(['success'=>true,'message'=>'Job berhasil dibuat.','data'=>['redirect'=>url('/jobs/'.$id)]]);
    }
    public function assign(string $id): void {
        $this->requireCsrf();if(!Auth::can('job.assign'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$uid=(int)Request::input('user_id');if(!$uid)Response::json(['success'=>false,'message'=>'Pilih technician.','errors'=>[]],422);$db=Database::connection();$t=Auth::tenantId();$v=$db->prepare("SELECT COUNT(*) FROM technicians WHERE tenant_id=? AND user_id=?");$v->execute([$t,$uid]);if(!(int)$v->fetchColumn())Response::json(['success'=>false,'message'=>'User bukan technician tenant ini.','errors'=>[]],422);$db->beginTransaction();try{$db->prepare("INSERT IGNORE INTO job_technicians(tenant_id,job_id,user_id,assigned_at) VALUES(?,?,?,NOW())")->execute([$t,(int)$id,$uid]);$db->prepare("UPDATE jobs SET status=IF(status='Draft','Assigned',status),updated_by=?,updated_at=NOW() WHERE id=? AND tenant_id=? AND deleted_at IS NULL")->execute([Auth::id(),(int)$id,$t]);$db->prepare("UPDATE technicians SET status='Assigned',updated_at=NOW() WHERE tenant_id=? AND user_id=?")->execute([$t,$uid]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}$ev=$db->prepare("SELECT j.job_number,c.email,u.name technician_name FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id JOIN users u ON u.id=? AND u.tenant_id=j.tenant_id WHERE j.id=? AND j.tenant_id=?");$ev->execute([$uid,(int)$id,$t]);$er=$ev->fetch();ActivityService::log('job',(int)$id,'technician_assigned','Technician assigned',['user_id'=>$uid]);EventService::emit((int)$t,'job.assigned',['job_number'=>$er['job_number']??('JOB#'.$id),'job_id'=>(int)$id,'technician_name'=>$er['technician_name']??'Technician'],$uid,$er['email']??null,'technician_assigned');Response::json(['success'=>true,'message'=>'Technician ditugaskan.','data'=>['reload'=>true]]);
    }
    public function unassign(string $id): void {$this->requireCsrf();if(!Auth::can('job.assign'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$uid=(int)Request::input('user_id');$db=Database::connection();$t=Auth::tenantId();$db->prepare("DELETE FROM job_technicians WHERE tenant_id=? AND job_id=? AND user_id=?")->execute([$t,(int)$id,$uid]);$db->prepare("UPDATE technicians SET status='Available',updated_at=NOW() WHERE tenant_id=? AND user_id=?")->execute([$t,$uid]);ActivityService::log('job',(int)$id,'technician_unassigned','Technician unassigned',['user_id'=>$uid]);Response::json(['success'=>true,'message'=>'Technician dilepas dari job.','data'=>['reload'=>true]]);}
    public function status(string $id): void {
        $this->requireCsrf();if(!Auth::can('job.complete')&&!Auth::can('job.assign'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$status=(string)Request::input('status');if(!in_array($status,$this->statuses,true))Response::json(['success'=>false,'message'=>'Status tidak valid.','errors'=>[]],422);$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT * FROM jobs WHERE id=? AND tenant_id=? AND deleted_at IS NULL");$s->execute([(int)$id,$t]);$job=$s->fetch();if(!$job)Response::json(['success'=>false,'message'=>'Job tidak ditemukan.','errors'=>[]],404);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$sets=['status=?','updated_by=?','updated_at=NOW()'];$args=[$status,Auth::id()];if($status==='On The Way')$sets[]='';if($status==='In Progress'&&!$job['started_at'])$sets[]='started_at=NOW()';if($status==='Completed'&&!$job['completed_at'])$sets[]='completed_at=NOW()';$sets=array_values(array_filter($sets));$args[]=(int)$id;$args[]=$t;$db->beginTransaction();try{$db->prepare("UPDATE jobs SET ".implode(',',$sets)." WHERE id=? AND tenant_id=?")->execute($args);$db->prepare("INSERT INTO job_status_history(tenant_id,job_id,old_status,new_status,changed_by,created_at) VALUES(?,?,?,?,?,NOW())")->execute([$t,(int)$id,$job['status'],$status,Auth::id()]);if(in_array($status,['Completed','Closed','Cancelled'],true))$db->prepare("UPDATE technicians t JOIN job_technicians jt ON jt.user_id=t.user_id AND jt.tenant_id=t.tenant_id SET t.status='Available',t.updated_at=NOW() WHERE jt.tenant_id=? AND jt.job_id=?")->execute([$t,(int)$id]);elseif($status==='On The Way')$db->prepare("UPDATE technicians t JOIN job_technicians jt ON jt.user_id=t.user_id AND jt.tenant_id=t.tenant_id SET t.status='On The Way',t.updated_at=NOW() WHERE jt.tenant_id=? AND jt.job_id=?")->execute([$t,(int)$id]);elseif($status==='In Progress')$db->prepare("UPDATE technicians t JOIN job_technicians jt ON jt.user_id=t.user_id AND jt.tenant_id=t.tenant_id SET t.status='Working',t.updated_at=NOW() WHERE jt.tenant_id=? AND jt.job_id=?")->execute([$t,(int)$id]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}AuditService::log('status_change','job',(int)$id,['status'=>$job['status']],['status'=>$status]);ActivityService::log('job',(int)$id,'status_changed',$job['status'].' → '.$status);if(in_array($status,['Scheduled','Completed'],true)){$ev=$db->prepare("SELECT j.job_number,c.email FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id WHERE j.id=? AND j.tenant_id=?");$ev->execute([(int)$id,$t]);$er=$ev->fetch();EventService::emit((int)$t,$status==='Completed'?'job.completed':'job.scheduled',['job_number'=>$er['job_number']??('JOB#'.$id),'job_id'=>(int)$id],null,$er['email']??null,$status==='Completed'?'job_completed':'job_scheduled');}Response::json(['success'=>true,'message'=>'Status job diperbarui.','data'=>['reload'=>true]]);
    }
    public function checkin(string $id): void {
        $this->requireCsrf();$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);
        $lat=Request::input('latitude');$lng=Request::input('longitude');$latVal=is_numeric($lat)?(float)$lat:null;$lngVal=is_numeric($lng)?(float)$lng:null;
        $site=$db->prepare("SELECT cs.latitude,cs.longitude FROM jobs j LEFT JOIN customer_sites cs ON cs.id=j.site_id AND cs.tenant_id=j.tenant_id WHERE j.id=? AND j.tenant_id=?");$site->execute([(int)$id,$t]);$siteRow=$site->fetch()?:[];$distance=null;
        if($latVal!==null&&$lngVal!==null&&isset($siteRow['latitude'],$siteRow['longitude'])&&$siteRow['latitude']!==null&&$siteRow['longitude']!==null){$distance=$this->distanceMeters($latVal,$lngVal,(float)$siteRow['latitude'],(float)$siteRow['longitude']);}
        $db->prepare("UPDATE jobs SET checkin_latitude=?,checkin_longitude=?,checked_in_at=NOW(),status='Arrived',updated_by=?,updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([$latVal,$lngVal,Auth::id(),(int)$id,$t]);
        ActivityService::log('job',(int)$id,'checked_in','Technician checked in',['latitude'=>$latVal,'longitude'=>$lngVal,'distance_from_site_m'=>$distance]);
        $message='Check-in tersimpan.';if($distance!==null){$message.=' Jarak dari lokasi customer: '.($distance<1000?round($distance).' m':number_format($distance/1000,2).' km').'.';}elseif($latVal===null||$lngVal===null){$message.=' GPS tidak tersedia; check-in tetap diterima dengan peringatan.';}elseif(empty($siteRow['latitude'])||empty($siteRow['longitude'])){$message.=' Koordinat customer site belum diatur.';}
        Response::json(['success'=>true,'message'=>$message,'data'=>['reload'=>true,'distance_m'=>$distance]]);
    }
    public function worklog(string $id): void {$this->requireCsrf();$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$activity=trim((string)Request::input('activity'));if($activity==='')Response::json(['success'=>false,'message'=>'Activity wajib diisi.','errors'=>[]],422);$db->prepare("INSERT INTO job_work_logs(tenant_id,job_id,technician_id,start_time,finish_time,activity,problem_found,action_taken,result,recommendation,created_at) VALUES(?,?,?,COALESCE(?,NOW()),?,?,?,?,?,?,NOW())")->execute([$t,(int)$id,Auth::id(),Request::input('start_time')?:null,Request::input('finish_time')?:null,$activity,Request::input('problem_found'),Request::input('action_taken'),Request::input('result'),Request::input('recommendation')]);ActivityService::log('job',(int)$id,'work_log_added',$activity);Response::json(['success'=>true,'message'=>'Work log ditambahkan.','data'=>['reload'=>true]]);}
    public function photo(string $id): void {$this->requireCsrf();$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);if(!isset($_FILES['photo']))Response::json(['success'=>false,'message'=>'Pilih photo.','errors'=>[]],422);$type=(string)Request::input('type','during');if(!in_array($type,['before','during','after'],true))$type='during';$path=UploadService::store($_FILES['photo'],$t,'jobs/'.$id.'/photos',6*1024*1024);$db->prepare("INSERT INTO job_photos(tenant_id,job_id,technician_id,type,path,caption,created_at) VALUES(?,?,?,?,?,?,NOW())")->execute([$t,(int)$id,Auth::id(),$type,$path,Request::input('caption')]);ActivityService::log('job',(int)$id,'photo_added',ucfirst($type).' photo uploaded');Response::json(['success'=>true,'message'=>'Photo tersimpan.','data'=>['reload'=>true]]);}
    public function material(string $id): void {$this->requireCsrf();$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);try{InventoryService::consume($t,(int)Request::input('warehouse_id'),(int)Request::input('item_id'),(float)Request::input('quantity'),(int)$id,Auth::id());}catch(\Throwable $e){Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}ActivityService::log('job',(int)$id,'material_used','Inventory material used',['item_id'=>(int)Request::input('item_id'),'quantity'=>(float)Request::input('quantity')]);Response::json(['success'=>true,'message'=>'Material usage tersimpan dan stock dikurangi.','data'=>['reload'=>true]]);}
    public function expense(string $id): void {$this->requireCsrf();$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$amount=(float)Request::input('amount');if($amount<=0)Response::json(['success'=>false,'message'=>'Amount harus lebih dari 0.','errors'=>[]],422);$receipt=null;if(isset($_FILES['receipt'])&&($_FILES['receipt']['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_OK)$receipt=UploadService::store($_FILES['receipt'],$t,'jobs/'.$id.'/expenses');$db->prepare("INSERT INTO job_expenses(tenant_id,job_id,user_id,category,amount,receipt,notes,expense_date,created_at) VALUES(?,?,?,?,?,?,?,COALESCE(?,CURDATE()),NOW())")->execute([$t,(int)$id,Auth::id(),Request::input('category','Other'),$amount,$receipt,Request::input('notes'),Request::input('expense_date')?:null]);ActivityService::log('job',(int)$id,'expense_added','Job expense added',['amount'=>$amount]);Response::json(['success'=>true,'message'=>'Expense tersimpan.','data'=>['reload'=>true]]);}
    public function signature(string $id): void {$this->requireCsrf();$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);if(!$this->canViewJob($db,$job))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$name=trim((string)Request::input('signer_name'));$data=(string)Request::input('signature_data');if($name===''||$data==='')Response::json(['success'=>false,'message'=>'Nama dan tanda tangan wajib.','errors'=>[]],422);try{$path=UploadService::storeDataUrl($data,$t,'jobs/'.$id.'/signatures');}catch(\Throwable $e){Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}$type=(string)Request::input('signature_type','customer');if(!in_array($type,['customer','technician'],true))$type='customer';$rating=Request::input('rating');$db->prepare("INSERT INTO job_signatures(tenant_id,job_id,signature_type,signer_name,signature_path,rating,feedback,signed_at,ip_address) VALUES(?,?,?,?,?,?,?,NOW(),?)")->execute([$t,(int)$id,$type,$name,$path,$rating!==''?(int)$rating:null,Request::input('feedback'),$_SERVER['REMOTE_ADDR']??null]);if($type==='customer')$db->prepare("UPDATE jobs SET status=IF(status='Completed','Customer Confirmation',status),updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([(int)$id,$t]);ActivityService::log('job',(int)$id,'signature_added',ucfirst($type).' signature captured');Response::json(['success'=>true,'message'=>'Tanda tangan tersimpan.','data'=>['reload'=>true]]);}
    public function invoice(string $id): void {$this->requireCsrf();if(!Auth::can('invoice.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$db=Database::connection();$t=Auth::tenantId();$job=$this->jobOrFail($db,$t,(int)$id);$ex=$db->prepare("SELECT id,invoice_number FROM invoices WHERE tenant_id=? AND job_id=? AND deleted_at IS NULL LIMIT 1");$ex->execute([$t,(int)$id]);if($v=$ex->fetch())Response::json(['success'=>true,'message'=>'Invoice sudah ada: '.$v['invoice_number'],'data'=>['redirect'=>url('/invoices/'.$v['id'])]]);$revenue=0;if($job['quotation_id']){$q=$db->prepare("SELECT grand_total FROM quotations WHERE id=? AND tenant_id=?");$q->execute([$job['quotation_id'],$t]);$revenue=(float)($q->fetchColumn()?:0);}if($revenue<=0)$revenue=(float)Request::input('total',0);if($revenue<=0)Response::json(['success'=>false,'message'=>'Masukkan total invoice karena job tidak memiliki quotation.','errors'=>[]],422);$num=NumberService::next($t,'invoice','INV');$db->beginTransaction();try{$db->prepare("INSERT INTO invoices(tenant_id,invoice_number,customer_id,job_id,quotation_id,invoice_date,due_date,subtotal,discount,tax,total,paid,balance,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,CURDATE(),DATE_ADD(CURDATE(),INTERVAL 14 DAY),?,0,0,?,0,?,'Draft',?,NOW(),NOW())")->execute([$t,$num,$job['customer_id'],(int)$id,$job['quotation_id']?:null,$revenue,$revenue,$revenue,Auth::id()]);$iid=(int)$db->lastInsertId();$db->prepare("INSERT INTO invoice_items(tenant_id,invoice_id,description,quantity,unit,unit_price,discount,tax,line_total) VALUES(?,?,'Service Job',1,'job',?,0,0,?)")->execute([$t,$iid,$revenue,$revenue]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}$ce=$db->prepare("SELECT email FROM customers WHERE id=? AND tenant_id=?");$ce->execute([$job['customer_id'],$t]);ActivityService::log('job',(int)$id,'invoice_created','Invoice '.$num.' generated',['invoice_id'=>$iid]);EventService::emit((int)$t,'invoice.created',['invoice_number'=>$num,'invoice_id'=>$iid,'job_number'=>$job['job_number'],'total'=>$revenue],null,$ce->fetchColumn()?:null,'invoice');Response::json(['success'=>true,'message'=>'Invoice '.$num.' dibuat.','data'=>['redirect'=>url('/invoices/'.$iid)]]);}
    public function warranty(string $id): void {$this->requireCsrf();if(!Auth::can('warranty.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$db=Database::connection();$t=Auth::tenantId();$this->jobOrFail($db,$t,(int)$id);$start=Request::input('warranty_start')?:date('Y-m-d');$end=Request::input('warranty_end');if(!$end)Response::json(['success'=>false,'message'=>'Warranty end wajib diisi.','errors'=>[]],422);$db->prepare("INSERT INTO warranties(tenant_id,job_id,warranty_start,warranty_end,coverage,terms,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'Active',NOW(),NOW())")->execute([$t,(int)$id,$start,$end,Request::input('coverage'),Request::input('terms')]);ActivityService::log('job',(int)$id,'warranty_created','Warranty created',['warranty_end'=>$end]);Response::json(['success'=>true,'message'=>'Warranty dibuat.','data'=>['reload'=>true]]);}
    private function jobOrFail(\PDO $db,int $t,int $id): array {$s=$db->prepare("SELECT * FROM jobs WHERE id=? AND tenant_id=? AND deleted_at IS NULL");$s->execute([$id,$t]);$j=$s->fetch();if(!$j)Response::json(['success'=>false,'message'=>'Job tidak ditemukan.','errors'=>[]],404);return $j;}
    private function isTechnician(\PDO $db,int $t,?int $uid): bool {$s=$db->prepare("SELECT COUNT(*) FROM technicians WHERE tenant_id=? AND user_id=?");$s->execute([$t,$uid]);return (bool)$s->fetchColumn();}
    private function canViewJob(\PDO $db,array $job): bool {if(!Auth::can('job.view'))return false;if(Auth::can('job.assign'))return true;if(!$this->isTechnician($db,(int)$job['tenant_id'],Auth::id()))return true;$s=$db->prepare("SELECT COUNT(*) FROM job_technicians WHERE tenant_id=? AND job_id=? AND user_id=?");$s->execute([$job['tenant_id'],$job['id'],Auth::id()]);return (bool)$s->fetchColumn();}
    private function forbidden(): void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}

    private function distanceMeters(float $lat1,float $lng1,float $lat2,float $lng2): float { $earth=6371000.0;$dLat=deg2rad($lat2-$lat1);$dLng=deg2rad($lng2-$lng1);$a=sin($dLat/2)**2+cos(deg2rad($lat1))*cos(deg2rad($lat2))*sin($dLng/2)**2;return $earth*2*atan2(sqrt($a),sqrt(1-$a)); }
}
