<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{NumberService,AuditService,ActivityService};
final class LeadController extends Controller {
    private array $statuses=['New','Contacted','Qualified','Proposal','Negotiation','Won','Lost'];
    public function index():void{if(!Auth::can('lead.view')){$this->forbidden();return;}$db=Database::connection();$s=$db->prepare("SELECT * FROM leads WHERE tenant_id=? AND deleted_at IS NULL ORDER BY follow_up_date IS NULL,follow_up_date,id DESC");$s->execute([Auth::tenantId()]);$board=[];foreach($this->statuses as $st)$board[$st]=[];foreach($s->fetchAll() as $r)$board[$r['status']][]=$r;$this->view('leads/index',['title'=>'Lead Pipeline','board'=>$board,'statuses'=>$this->statuses]);}
    public function create():never{$this->requireCsrf();if(!Auth::can('lead.create'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$name=trim((string)Request::input('customer_name'));if($name==='')Response::json(['success'=>false,'message'=>'Customer name wajib diisi.'],422);$t=(int)Auth::tenantId();$num=NumberService::next($t,'lead','LEAD');$db=Database::connection();$db->prepare("INSERT INTO leads(tenant_id,lead_number,customer_name,company,phone,whatsapp,email,source,service_interest,estimated_value,sales_user_id,status,follow_up_date,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$t,$num,$name,Request::input('company'),Request::input('phone'),Request::input('whatsapp'),Request::input('email'),Request::input('source'),Request::input('service_interest'),(float)Request::input('estimated_value',0),Auth::id(),Request::input('status','New'),Request::input('follow_up_date')?:null,Request::input('notes')]);$id=(int)$db->lastInsertId();AuditService::log('create','lead',$id,null,['lead_number'=>$num]);Response::json(['success'=>true,'message'=>'Lead '.$num.' created.','data'=>['reload'=>true]]);}
    public function status(string $id):never{$this->requireCsrf();if(!Auth::can('lead.edit'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$status=(string)Request::input('status');if(!in_array($status,$this->statuses,true))Response::json(['success'=>false,'message'=>'Invalid lead status'],422);$db=Database::connection();$t=(int)Auth::tenantId();$s=$db->prepare("SELECT * FROM leads WHERE id=? AND tenant_id=? AND deleted_at IS NULL");$s->execute([(int)$id,$t]);$old=$s->fetch();if(!$old)Response::json(['success'=>false,'message'=>'Lead not found'],404);$db->prepare("UPDATE leads SET status=?,updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([$status,(int)$id,$t]);AuditService::log('status','lead',(int)$id,$old,['status'=>$status]);Response::json(['success'=>true,'message'=>'Lead moved to '.$status,'data'=>[]]);}
    public function convert(string $id): void {$this->requireCsrf();if(!Auth::can('lead.edit')&&!Auth::can('customer.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$db=Database::connection();$t=(int)Auth::tenantId();$s=$db->prepare("SELECT * FROM leads WHERE id=? AND tenant_id=? AND deleted_at IS NULL");$s->execute([(int)$id,$t]);$lead=$s->fetch();if(!$lead)Response::json(['success'=>false,'message'=>'Lead tidak ditemukan.','errors'=>[]],404);$existing=$db->prepare("SELECT id,name FROM customers WHERE tenant_id=? AND deleted_at IS NULL AND ((email IS NOT NULL AND email=? AND ?<>'') OR (phone IS NOT NULL AND phone=? AND ?<>'')) LIMIT 1");$existing->execute([$t,$lead['email'],$lead['email']??'',$lead['phone'],$lead['phone']??'']);if($c=$existing->fetch()){Response::json(['success'=>false,'message'=>'Kemungkinan customer sudah ada: '.$c['name'],'errors'=>[]],422);} $num=NumberService::next($t,'customer','CUS');$db->beginTransaction();try{$db->prepare("INSERT INTO customers(tenant_id,customer_code,customer_type,name,company,phone,whatsapp,email,notes,status,created_by,created_at,updated_at) VALUES(?,?,'Company',?,?,?,?,?,?,'active',?,NOW(),NOW())")->execute([$t,$num,$lead['customer_name'],$lead['company'],$lead['phone'],$lead['whatsapp'],$lead['email'],'Converted from '.$lead['lead_number'].'. '.$lead['notes'],Auth::id()]);$cid=(int)$db->lastInsertId();$db->prepare("UPDATE leads SET status='Won',updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([(int)$id,$t]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}AuditService::log('convert','lead',(int)$id,$lead,['customer_id'=>$cid]);ActivityService::log('customer',$cid,'created_from_lead','Customer converted from '.$lead['lead_number']);Response::json(['success'=>true,'message'=>'Lead menjadi customer '.$num.'.','data'=>['redirect'=>url('/customers')]]);}
    private function forbidden():void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
