<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Request,Response,Session};
use App\Services\MailService;
final class PasswordController extends Controller {
    public function forgotForm():void{$this->view('auth/forgot',['title'=>'Forgot Password']);}
    public function forgot():void{$this->requireCsrf();$email=strtolower(trim((string)Request::input('email')));$db=Database::connection();$s=$db->prepare("SELECT id,tenant_id,name,email FROM users WHERE email=? AND status='active' AND deleted_at IS NULL LIMIT 1");$s->execute([$email]);$u=$s->fetch();$devLink=null;if($u){$raw=bin2hex(random_bytes(32));$hash=hash('sha256',$raw);$db->prepare("UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=? AND used_at IS NULL")->execute([$u['id']]);$db->prepare("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at,created_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 60 MINUTE),NOW())")->execute([$u['id'],$hash]);$link=url('/reset-password?token='.urlencode($raw));MailService::sendTenant($u['tenant_id']?(int)$u['tenant_id']:null,$u['email'],'ServicePro password reset','<p>Hello '.htmlspecialchars($u['name'],ENT_QUOTES,'UTF-8').',</p><p>Use the link below within 60 minutes to reset your password.</p><p><a href="'.htmlspecialchars($link,ENT_QUOTES,'UTF-8').'">Reset Password</a></p>');if(config('env')==='development')$devLink=$link;}Session::flash('success','Jika email terdaftar, instruksi reset password telah dibuat.');if($devLink)Session::flash('reset_link',$devLink);Response::redirect('/forgot-password');}
    public function resetForm():void{$token=(string)($_GET['token']??'');$valid=$this->find($token);$this->view('auth/reset',['title'=>'Reset Password','token'=>$token,'valid'=>(bool)$valid]);}
    public function reset():void{$this->requireCsrf();$token=(string)Request::input('token');$password=(string)Request::input('password');$confirm=(string)Request::input('password_confirmation');if(strlen($password)<8||$password!==$confirm){Session::flash('error','Password minimal 8 karakter dan konfirmasi harus sama.');Response::redirect('/reset-password?token='.urlencode($token));}$r=$this->find($token);if(!$r){Session::flash('error','Reset link tidak valid atau sudah kedaluwarsa.');Response::redirect('/forgot-password');}$db=Database::connection();$db->beginTransaction();try{$db->prepare("UPDATE users SET password_hash=?,updated_at=NOW() WHERE id=?")->execute([password_hash($password,PASSWORD_DEFAULT),$r['user_id']]);$db->prepare("UPDATE password_reset_tokens SET used_at=NOW() WHERE id=?")->execute([$r['id']]);$db->prepare("UPDATE user_sessions SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL")->execute([$r['user_id']]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}Session::flash('success','Password berhasil diubah. Silakan login.');Response::redirect('/login');}
    private function find(string $token):?array{if(strlen($token)<32)return null;$s=Database::connection()->prepare("SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>NOW() LIMIT 1");$s->execute([hash('sha256',$token)]);return $s->fetch()?:null;}
}
