<?php
namespace App\Controllers;
use App\Core\{Database,Auth};
use App\Services\SimplePdfService;
final class PrintController {
    private function branding(array $r,array $attachments=[]):array{return ['logo_path'=>$r['logo']??null,'footer'=>$r['invoice_footer']??null,'attachments'=>array_values(array_filter($attachments,fn($x)=>!empty($x['path'])))];}
    public function invoice(string $id): never {
        $db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT i.*,c.name customer_name,c.billing_address,t.name company_name,t.address company_address,t.tax_number company_tax,t.logo,t.signature,t.stamp,t.invoice_footer FROM invoices i JOIN customers c ON c.id=i.customer_id AND c.tenant_id=i.tenant_id JOIN tenants t ON t.id=i.tenant_id WHERE i.id=? AND i.tenant_id=? AND i.deleted_at IS NULL");$s->execute([(int)$id,$t]);$i=$s->fetch();if(!$i){http_response_code(404);exit('Invoice not found');}$q=$db->prepare("SELECT * FROM invoice_items WHERE invoice_id=? AND tenant_id=? ORDER BY id");$q->execute([(int)$id,$t]);$lines=['INVOICE '.$i['invoice_number'],'Customer: '.$i['customer_name'],'Billing Address: '.($i['billing_address']??''),'Invoice Date: '.$i['invoice_date'].'   Due: '.($i['due_date']??'-'),''];foreach($q->fetchAll() as $r)$lines[]=sprintf('%s | %s %s x %s | %s',$r['description'],$r['quantity'],$r['unit']??'',money($r['unit_price']),money($r['line_total']));$lines[]='';$lines[]='Subtotal: '.money($i['subtotal']);$lines[]='Discount: '.money($i['discount']);$lines[]='Tax: '.money($i['tax']);$lines[]='TOTAL: '.money($i['total']);$lines[]='Paid: '.money($i['paid']);$lines[]='Balance: '.money($i['balance']);$lines[]='Status: '.$i['status'];$lines[]='';$lines[]='Company: '.$i['company_name'];$lines[]='Address: '.($i['company_address']??'');if($i['company_tax'])$lines[]='Tax ID: '.$i['company_tax'];SimplePdfService::output($i['invoice_number'].'.pdf',$lines,$i['company_name'],$this->branding($i,[['path'=>$i['signature'],'label'=>'Authorized Signature'],['path'=>$i['stamp'],'label'=>'Company Stamp']]));
    }
    public function quotation(string $id): never {
        $db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT q.*,c.name customer_name,c.billing_address,t.name company_name,t.address company_address,t.logo,t.signature,t.stamp,t.invoice_footer FROM quotations q JOIN customers c ON c.id=q.customer_id AND c.tenant_id=q.tenant_id JOIN tenants t ON t.id=q.tenant_id WHERE q.id=? AND q.tenant_id=? AND q.deleted_at IS NULL");$s->execute([(int)$id,$t]);$qte=$s->fetch();if(!$qte){http_response_code(404);exit('Quotation not found');}$q=$db->prepare("SELECT * FROM quotation_items WHERE quotation_id=? AND tenant_id=? ORDER BY id");$q->execute([(int)$id,$t]);$lines=['QUOTATION '.$qte['quotation_number'],'Customer: '.$qte['customer_name'],'Date: '.$qte['quotation_date'].'   Valid Until: '.($qte['valid_until']??'-'),''];foreach($q->fetchAll() as $r)$lines[]=sprintf('%s | %s %s x %s | %s',$r['description'],$r['quantity'],$r['unit']??'',money($r['unit_price']),money($r['line_total']));$lines[]='';$lines[]='Grand Total: '.money($qte['grand_total']);$lines[]='Status: '.$qte['status'];$lines[]='Terms: '.($qte['terms']??'');SimplePdfService::output($qte['quotation_number'].'.pdf',$lines,$qte['company_name'],$this->branding($qte,[['path'=>$qte['signature'],'label'=>'Authorized Signature'],['path'=>$qte['stamp'],'label'=>'Company Stamp']]));
    }
    public function serviceReport(string $id): never {
        $db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT j.*,c.name customer_name,c.service_address,t.name company_name,t.logo,t.invoice_footer FROM jobs j JOIN customers c ON c.id=j.customer_id AND c.tenant_id=j.tenant_id JOIN tenants t ON t.id=j.tenant_id WHERE j.id=? AND j.tenant_id=? AND j.deleted_at IS NULL");$s->execute([(int)$id,$t]);$j=$s->fetch();if(!$j){http_response_code(404);exit('Job not found');}$logs=$db->prepare("SELECT activity,problem_found,action_taken,result,recommendation FROM job_work_logs WHERE job_id=? AND tenant_id=? ORDER BY id");$logs->execute([(int)$id,$t]);$m=$db->prepare("SELECT i.item_name,jm.quantity,i.unit FROM job_materials jm JOIN items i ON i.id=jm.item_id AND i.tenant_id=jm.tenant_id WHERE jm.job_id=? AND jm.tenant_id=?");$m->execute([(int)$id,$t]);$sig=$db->prepare("SELECT signer_name,signature_type,rating,feedback,signed_at,signature_path FROM job_signatures WHERE job_id=? AND tenant_id=? ORDER BY id");$sig->execute([(int)$id,$t]);$signatures=$sig->fetchAll();$lines=['SERVICE REPORT','Job: '.$j['job_number'],'Customer: '.$j['customer_name'],'Address: '.($j['service_address']??''),'Service Date: '.($j['completed_at']??$j['scheduled_date']??'-'),'Problem / Work: '.$j['description'],'','WORK LOGS'];foreach($logs->fetchAll() as $l){$lines[]='Activity: '.($l['activity']??'');if($l['problem_found'])$lines[]='Problem: '.$l['problem_found'];if($l['action_taken'])$lines[]='Action: '.$l['action_taken'];if($l['result'])$lines[]='Result: '.$l['result'];if($l['recommendation'])$lines[]='Recommendation: '.$l['recommendation'];$lines[]='';}$lines[]='MATERIALS USED';foreach($m->fetchAll() as $r)$lines[]=$r['item_name'].' - '.$r['quantity'].' '.$r['unit'];$lines[]='';$lines[]='SIGNATURE / CONFIRMATION';$attachments=[];foreach($signatures as $r){$lines[]=ucfirst($r['signature_type']).': '.$r['signer_name'].' · '.($r['rating']?'Rating '.$r['rating'].'/5 · ':'').$r['signed_at'];if($r['feedback'])$lines[]='Feedback: '.$r['feedback'];$attachments[]=['path'=>$r['signature_path'],'label'=>ucfirst($r['signature_type']).' · '.$r['signer_name']];}SimplePdfService::output('SERVICE-'.$j['job_number'].'.pdf',$lines,$j['company_name'],$this->branding($j,$attachments));
    }
}
