<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{NumberService,AuditService,InventoryService,ActivityService};
final class PurchaseController extends Controller {
    public function index(): void {
        if(!Auth::can('purchase.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$pr=$db->prepare("SELECT pr.*,u.name requester_name,b.name branch_name,(SELECT COUNT(*) FROM purchase_request_items x WHERE x.purchase_request_id=pr.id AND x.tenant_id=pr.tenant_id) item_count FROM purchase_requests pr JOIN users u ON u.id=pr.requester_id LEFT JOIN branches b ON b.id=pr.branch_id WHERE pr.tenant_id=? ORDER BY pr.id DESC");$pr->execute([$t]);$po=$db->prepare("SELECT po.*,v.vendor_name,pr.request_number,(SELECT COUNT(*) FROM purchase_order_items x WHERE x.purchase_order_id=po.id AND x.tenant_id=po.tenant_id) item_count FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id AND v.tenant_id=po.tenant_id LEFT JOIN purchase_requests pr ON pr.id=po.purchase_request_id AND pr.tenant_id=po.tenant_id WHERE po.tenant_id=? ORDER BY po.id DESC");$po->execute([$t]);$items=$db->prepare("SELECT id,sku,item_name,unit,purchase_price FROM items WHERE tenant_id=? AND deleted_at IS NULL ORDER BY item_name");$items->execute([$t]);$vendors=$db->prepare("SELECT id,vendor_name FROM vendors WHERE tenant_id=? AND deleted_at IS NULL ORDER BY vendor_name");$vendors->execute([$t]);$wh=$db->prepare("SELECT id,name FROM warehouses WHERE tenant_id=? AND deleted_at IS NULL AND status='active' ORDER BY name");$wh->execute([$t]);$branches=$db->prepare("SELECT id,name FROM branches WHERE tenant_id=? AND deleted_at IS NULL ORDER BY name");$branches->execute([$t]);$this->view('purchasing/index',['title'=>'Purchasing','requests'=>$pr->fetchAll(),'orders'=>$po->fetchAll(),'items'=>$items->fetchAll(),'vendors'=>$vendors->fetchAll(),'warehouses'=>$wh->fetchAll(),'branches'=>$branches->fetchAll()]);
    }
    public function request(): void {
        $this->requireCsrf();if(!Auth::can('purchase.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$items=$_POST['items']??[];if(!is_array($items)||!$items)Response::json(['success'=>false,'message'=>'Minimal satu item diperlukan.','errors'=>[]],422);$t=(int)Auth::tenantId();$db=Database::connection();$num=NumberService::next($t,'purchase_request','PR');$db->beginTransaction();try{$db->prepare("INSERT INTO purchase_requests(tenant_id,request_number,requester_id,branch_id,status,notes,created_at,updated_at) VALUES(?,?,?,?, 'Request',?,NOW(),NOW())")->execute([$t,$num,Auth::id(),Request::input('branch_id')?:null,Request::input('notes')]);$id=(int)$db->lastInsertId();$ins=$db->prepare("INSERT INTO purchase_request_items(tenant_id,purchase_request_id,item_id,description,quantity,unit) VALUES(?,?,?,?,?,?)");$valid=0;foreach($items as $r){$qty=(float)($r['quantity']??0);$desc=trim((string)($r['description']??''));$itemId=(int)($r['item_id']??0)?:null;if($qty<=0||(!$itemId&&$desc===''))continue;if($itemId&&$desc===''){$x=$db->prepare("SELECT item_name,unit FROM items WHERE id=? AND tenant_id=?");$x->execute([$itemId,$t]);if($it=$x->fetch()){$desc=$it['item_name'];$r['unit']=$r['unit']?:$it['unit'];}}$ins->execute([$t,$id,$itemId,$desc,$qty,$r['unit']??null]);$valid++;}if(!$valid)throw new \RuntimeException('Tidak ada item PR yang valid.');$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}AuditService::log('create','purchase_request',$id,null,['request_number'=>$num]);Response::json(['success'=>true,'message'=>'Purchase Request '.$num.' dibuat.','data'=>['reload'=>true]]);
    }
    public function approve(string $id): void {$this->requireCsrf();if(!Auth::can('purchase.approve'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$status=(string)Request::input('status','Approved');if(!in_array($status,['Approved','Rejected','Purchasing'],true))$status='Approved';Database::connection()->prepare("UPDATE purchase_requests SET status=?,updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([$status,(int)$id,Auth::tenantId()]);Response::json(['success'=>true,'message'=>'PR status: '.$status,'data'=>['reload'=>true]]);}
    public function order(): void {
        $this->requireCsrf();if(!Auth::can('purchase.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$t=(int)Auth::tenantId();$vendor=(int)Request::input('vendor_id');$prId=(int)Request::input('purchase_request_id',0)?:null;$items=$_POST['items']??[];if(!$vendor||!is_array($items)||!$items)Response::json(['success'=>false,'message'=>'Vendor dan item PO wajib.','errors'=>[]],422);$num=NumberService::next($t,'purchase_order','PO');$db=Database::connection();$clean=[];$subtotal=0;foreach($items as $r){$qty=(float)($r['quantity']??0);$price=(float)($r['unit_price']??0);$desc=trim((string)($r['description']??''));$itemId=(int)($r['item_id']??0)?:null;if($qty<=0||(!$itemId&&$desc===''))continue;if($itemId&&$desc===''){$x=$db->prepare("SELECT item_name,purchase_price FROM items WHERE id=? AND tenant_id=?");$x->execute([$itemId,$t]);if($it=$x->fetch()){$desc=$it['item_name'];if($price<=0)$price=(float)$it['purchase_price'];}}$line=$qty*$price;$subtotal+=$line;$clean[]=[$itemId,$desc,$qty,$price,$line];}if(!$clean)Response::json(['success'=>false,'message'=>'Item PO tidak valid.','errors'=>[]],422);$tax=(float)Request::input('tax',0);$total=$subtotal+$tax;$db->beginTransaction();try{$db->prepare("INSERT INTO purchase_orders(tenant_id,po_number,vendor_id,purchase_request_id,order_date,expected_date,subtotal,tax,total,status,created_at,updated_at) VALUES(?,?,?,?,CURDATE(),?,?,?,?, 'Draft',NOW(),NOW())")->execute([$t,$num,$vendor,$prId,Request::input('expected_date')?:null,$subtotal,$tax,$total]);$poid=(int)$db->lastInsertId();$ins=$db->prepare("INSERT INTO purchase_order_items(tenant_id,purchase_order_id,item_id,description,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?)");foreach($clean as $r)$ins->execute([$t,$poid,...$r]);if($prId)$db->prepare("UPDATE purchase_requests SET status='PO Created',updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([$prId,$t]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}AuditService::log('create','purchase_order',$poid,null,['po_number'=>$num]);Response::json(['success'=>true,'message'=>'Purchase Order '.$num.' dibuat.','data'=>['reload'=>true]]);
    }
    public function receive(string $id): void {
        $this->requireCsrf();if(!Auth::can('purchase.receive'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$t=(int)Auth::tenantId();$warehouse=(int)Request::input('warehouse_id');if(!$warehouse)Response::json(['success'=>false,'message'=>'Warehouse wajib dipilih.','errors'=>[]],422);$db=Database::connection();$po=$db->prepare("SELECT * FROM purchase_orders WHERE id=? AND tenant_id=?");$po->execute([(int)$id,$t]);$order=$po->fetch();if(!$order)Response::json(['success'=>false,'message'=>'PO tidak ditemukan.','errors'=>[]],404);$q=$db->prepare("SELECT poi.*,COALESCE((SELECT SUM(gri.quantity) FROM goods_receipt_items gri WHERE gri.tenant_id=poi.tenant_id AND gri.purchase_order_item_id=poi.id),0) received_qty FROM purchase_order_items poi WHERE poi.purchase_order_id=? AND poi.tenant_id=?");$q->execute([(int)$id,$t]);$lines=$q->fetchAll();$num=NumberService::next($t,'goods_receipt','GR');$db->beginTransaction();try{$db->prepare("INSERT INTO goods_receipts(tenant_id,receipt_number,purchase_order_id,warehouse_id,received_date,received_by,notes,created_at) VALUES(?,?,?,?,CURDATE(),?,?,NOW())")->execute([$t,$num,(int)$id,$warehouse,Auth::id(),Request::input('notes')]);$rid=(int)$db->lastInsertId();$ins=$db->prepare("INSERT INTO goods_receipt_items(tenant_id,goods_receipt_id,purchase_order_item_id,item_id,quantity,unit_cost,created_at) VALUES(?,?,?,?,?,?,NOW())");$receivedAny=false;foreach($lines as $ln){$outstanding=(float)$ln['quantity']-(float)$ln['received_qty'];if($outstanding<=0||!$ln['item_id'])continue;$ins->execute([$t,$rid,$ln['id'],$ln['item_id'],$outstanding,$ln['unit_price']]);InventoryService::receive($t,$warehouse,(int)$ln['item_id'],$outstanding,(float)$ln['unit_price'],$rid,Auth::id());$receivedAny=true;}if(!$receivedAny)throw new \RuntimeException('Tidak ada outstanding stock item yang dapat diterima.');$db->prepare("UPDATE purchase_orders SET status='Received',updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([(int)$id,$t]);if($order['purchase_request_id'])$db->prepare("UPDATE purchase_requests SET status='Received',updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([$order['purchase_request_id'],$t]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();Response::json(['success'=>false,'message'=>$e->getMessage(),'errors'=>[]],422);}Response::json(['success'=>true,'message'=>'Goods receipt '.$num.' selesai; stock telah bertambah.','data'=>['reload'=>true]]);
    }
    private function forbidden(): void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
