<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{AuditService,NumberService,ActivityService,EventService};
final class QuotationController extends Controller {
    public function index(): void {
        if(!Auth::can('quotation.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT q.*,c.name customer_name,u.name sales_name FROM quotations q JOIN customers c ON c.id=q.customer_id AND c.tenant_id=q.tenant_id LEFT JOIN users u ON u.id=q.sales_user_id AND u.tenant_id=q.tenant_id WHERE q.tenant_id=? AND q.deleted_at IS NULL ORDER BY q.id DESC");$s->execute([$t]);$c=$db->prepare("SELECT id,name FROM customers WHERE tenant_id=? AND deleted_at IS NULL ORDER BY name");$c->execute([$t]);$this->view('quotations/index',['title'=>'Quotations','quotations'=>$s->fetchAll(),'customers'=>$c->fetchAll()]);
    }
    public function show(string $id): void {
        if(!Auth::can('quotation.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$q=$db->prepare("SELECT q.*,c.name customer_name,c.email customer_email,c.phone customer_phone,c.billing_address FROM quotations q JOIN customers c ON c.id=q.customer_id AND c.tenant_id=q.tenant_id WHERE q.id=? AND q.tenant_id=? AND q.deleted_at IS NULL");$q->execute([(int)$id,$t]);$quote=$q->fetch();if(!$quote){http_response_code(404);require BASE_PATH.'/app/Views/errors/404.php';return;}$it=$db->prepare("SELECT * FROM quotation_items WHERE quotation_id=? AND tenant_id=? ORDER BY id");$it->execute([(int)$id,$t]);$ap=$db->prepare("SELECT * FROM quotation_approvals WHERE quotation_id=? AND tenant_id=? ORDER BY id DESC");$ap->execute([(int)$id,$t]);$this->view('quotations/show',['title'=>$quote['quotation_number'],'quote'=>$quote,'items'=>$it->fetchAll(),'approvals'=>$ap->fetchAll()]);
    }
    public function store(): void {
        $this->requireCsrf();if(!Auth::can('quotation.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$t=Auth::tenantId();$customer=(int)Request::input('customer_id');$items=$_POST['items']??[];if(!$customer||!is_array($items)||!$items)Response::json(['success'=>false,'message'=>'Customer dan minimal satu item wajib diisi.','errors'=>[]],422);$db=Database::connection();$num=NumberService::next($t,'quotation','QUO');$subtotal=0;$taxTotal=0;$discountTotal=0;$clean=[];foreach($items as $r){$d=trim((string)($r['description']??''));$q=(float)($r['quantity']??0);$p=(float)($r['unit_price']??0);$disc=(float)($r['discount']??0);$tax=(float)($r['tax']??0);if($d===''||$q<=0)continue;$line=max(0,$q*$p-$disc+$tax);$subtotal+=$q*$p;$discountTotal+=$disc;$taxTotal+=$tax;$clean[]=[$r['item_type']??'service',$d,$q,$r['unit']??'job',$p,$disc,$tax,$line];}if(!$clean)Response::json(['success'=>false,'message'=>'Item quotation tidak valid.','errors'=>[]],422);$grand=max(0,$subtotal-$discountTotal+$taxTotal);
        $db->beginTransaction();try{$db->prepare("INSERT INTO quotations(tenant_id,quotation_number,customer_id,survey_id,quotation_date,valid_until,sales_user_id,status,subtotal,discount,tax,grand_total,terms,notes,created_at,updated_at) VALUES(?,?,?,NULL,CURDATE(),?,?, 'Draft',?,?,?,?,?,?,NOW(),NOW())")->execute([$t,$num,$customer,Request::input('valid_until')?:date('Y-m-d',strtotime('+14 days')),Auth::id(),$subtotal,$discountTotal,$taxTotal,$grand,Request::input('terms'),Request::input('notes')]);$qid=(int)$db->lastInsertId();$ins=$db->prepare("INSERT INTO quotation_items(tenant_id,quotation_id,item_type,description,quantity,unit,unit_price,discount,tax,line_total) VALUES(?,?,?,?,?,?,?,?,?,?)");foreach($clean as $r)$ins->execute([$t,$qid,...$r]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}AuditService::log('create','quotation',$qid,null,['quotation_number'=>$num,'grand_total'=>$grand]);ActivityService::log('quotation',$qid,'created','Quotation created');Response::json(['success'=>true,'message'=>'Quotation berhasil dibuat.','data'=>['redirect'=>url('/quotations/'.$qid)]]);
    }
    public function status(string $id): void {
        $this->requireCsrf();if(!Auth::can('quotation.edit')&&!Auth::can('quotation.approve'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$status=(string)Request::input('status');$allowed=['Draft','Internal Review','Sent','Viewed','Approved','Rejected','Expired'];if(!in_array($status,$allowed,true))Response::json(['success'=>false,'message'=>'Status invalid.','errors'=>[]],422);$db=Database::connection();$t=Auth::tenantId();$db->prepare("UPDATE quotations SET status=?,updated_at=NOW() WHERE id=? AND tenant_id=? AND deleted_at IS NULL")->execute([$status,(int)$id,$t]);ActivityService::log('quotation',(int)$id,'status_changed','Quotation status changed',['status'=>$status]);if($status==='Sent'){$e=$db->prepare("SELECT q.quotation_number,q.grand_total,c.email FROM quotations q JOIN customers c ON c.id=q.customer_id AND c.tenant_id=q.tenant_id WHERE q.id=? AND q.tenant_id=?");$e->execute([(int)$id,$t]);if($r=$e->fetch())EventService::emit((int)$t,'quotation.sent',['quotation_number'=>$r['quotation_number'],'quotation_id'=>(int)$id,'grand_total'=>$r['grand_total']],null,$r['email']?:null,'quotation');}Response::json(['success'=>true,'message'=>'Status quotation diperbarui.','data'=>['reload'=>true]]);
    }
    public function approve(string $id): void {
        $this->requireCsrf();if(!Auth::can('quotation.approve'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT q.id,q.status,q.quotation_number,q.grand_total,c.email FROM quotations q JOIN customers c ON c.id=q.customer_id AND c.tenant_id=q.tenant_id WHERE q.id=? AND q.tenant_id=? AND q.deleted_at IS NULL");$s->execute([(int)$id,$t]);$approvedQuote=$s->fetch();if(!$approvedQuote)Response::json(['success'=>false,'message'=>'Quotation tidak ditemukan.','errors'=>[]],404);$name=trim((string)Request::input('customer_name','Internal approval'));$db->beginTransaction();try{$db->prepare("UPDATE quotations SET status='Approved',updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([(int)$id,$t]);$db->prepare("INSERT INTO quotation_approvals(tenant_id,quotation_id,action,customer_name,customer_email,notes,approved_at,ip_address) VALUES(?,?,'Approved',?,?,?,NOW(),?)")->execute([$t,(int)$id,$name,Request::input('customer_email'),Request::input('notes'),$_SERVER['REMOTE_ADDR']??null]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}ActivityService::log('quotation',(int)$id,'approved','Quotation approved');EventService::emit((int)$t,'quotation.approved',['quotation_number'=>$approvedQuote['quotation_number'],'quotation_id'=>(int)$id,'grand_total'=>$approvedQuote['grand_total']],null,$approvedQuote['email']?:null,'quotation');Response::json(['success'=>true,'message'=>'Quotation disetujui.','data'=>['reload'=>true]]);
    }
    public function convert(string $id): void {
        $this->requireCsrf();if(!Auth::can('quotation.convert')&&!Auth::can('job.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT q.*,sv.service_request_id FROM quotations q LEFT JOIN surveys sv ON sv.id=q.survey_id AND sv.tenant_id=q.tenant_id WHERE q.id=? AND q.tenant_id=? AND q.deleted_at IS NULL");$s->execute([(int)$id,$t]);$q=$s->fetch();if(!$q)Response::json(['success'=>false,'message'=>'Quotation tidak ditemukan.','errors'=>[]],404);if($q['status']!=='Approved')Response::json(['success'=>false,'message'=>'Quotation harus Approved sebelum dibuat Job.','errors'=>[]],422);$existing=$db->prepare("SELECT id,job_number FROM jobs WHERE tenant_id=? AND quotation_id=? AND deleted_at IS NULL LIMIT 1");$existing->execute([$t,(int)$id]);if($j=$existing->fetch())Response::json(['success'=>true,'message'=>'Job sudah pernah dibuat: '.$j['job_number'],'data'=>['redirect'=>url('/jobs/'.$j['id'])]]);$num=NumberService::next($t,'job','JOB');$desc='Work generated from quotation '.$q['quotation_number'];$db->beginTransaction();try{$db->prepare("INSERT INTO jobs(tenant_id,job_number,customer_id,service_request_id,quotation_id,description,priority,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'Normal','Draft',?,NOW(),NOW())")->execute([$t,$num,$q['customer_id'],$q['service_request_id']?:null,(int)$id,$desc,Auth::id()]);$jid=(int)$db->lastInsertId();if($q['service_request_id'])$db->prepare("UPDATE service_requests SET status='Approved',updated_by=?,updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([Auth::id(),$q['service_request_id'],$t]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}ActivityService::log('job',$jid,'created_from_quotation','Job generated from quotation',['quotation_id'=>(int)$id]);Response::json(['success'=>true,'message'=>'Job '.$num.' berhasil dibuat.','data'=>['redirect'=>url('/jobs/'.$jid)]]);
    }
    private function forbidden(): void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
