<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{AuditService,NumberService,ActivityService};
final class SurveyController extends Controller {
    public function index(): void {
        if(!Auth::can('survey.view')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();
        $s=$db->prepare("SELECT sv.*,c.name customer_name,sr.request_number,u.name surveyor_name FROM surveys sv JOIN customers c ON c.id=sv.customer_id AND c.tenant_id=sv.tenant_id LEFT JOIN service_requests sr ON sr.id=sv.service_request_id AND sr.tenant_id=sv.tenant_id LEFT JOIN users u ON u.id=sv.surveyor_id AND u.tenant_id=sv.tenant_id WHERE sv.tenant_id=? AND sv.deleted_at IS NULL ORDER BY sv.id DESC");$s->execute([$t]);
        $c=$db->prepare("SELECT id,name FROM customers WHERE tenant_id=? AND deleted_at IS NULL ORDER BY name");$c->execute([$t]);
        $r=$db->prepare("SELECT id,request_number FROM service_requests WHERE tenant_id=? AND deleted_at IS NULL AND status NOT IN('Completed','Cancelled','Closed') ORDER BY id DESC");$r->execute([$t]);
        $u=$db->prepare("SELECT id,name FROM users WHERE tenant_id=? AND deleted_at IS NULL AND status='active' ORDER BY name");$u->execute([$t]);
        $this->view('surveys/index',['title'=>'Site Surveys','surveys'=>$s->fetchAll(),'customers'=>$c->fetchAll(),'requests'=>$r->fetchAll(),'users'=>$u->fetchAll()]);
    }
    public function store(): void {
        $this->requireCsrf();if(!Auth::can('survey.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$t=Auth::tenantId();$customer=(int)Request::input('customer_id');if(!$customer)Response::json(['success'=>false,'message'=>'Customer wajib dipilih.','errors'=>[]],422);$db=Database::connection();$num=NumberService::next($t,'survey','SUR');$requestId=(int)Request::input('service_request_id',0)?:null;
        $db->beginTransaction();try{$db->prepare("INSERT INTO surveys(tenant_id,survey_number,service_request_id,customer_id,site_id,surveyor_id,survey_date,findings,recommended_solution,estimated_materials,estimated_labor,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,COALESCE(?,CURDATE()),?,?,?,?,?,NOW(),NOW())")->execute([$t,$num,$requestId,$customer,Request::input('site_id')?:null,Request::input('surveyor_id')?:Auth::id(),Request::input('survey_date')?:null,Request::input('findings'),Request::input('recommended_solution'),Request::input('estimated_materials'),(float)Request::input('estimated_labor',0),Request::input('notes')]);$id=(int)$db->lastInsertId();if($requestId)$db->prepare("UPDATE service_requests SET status='Need Survey',updated_by=?,updated_at=NOW() WHERE id=? AND tenant_id=?")->execute([Auth::id(),$requestId,$t]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}AuditService::log('create','survey',$id,null,['survey_number'=>$num]);ActivityService::log('survey',$id,'created','Site survey created');Response::json(['success'=>true,'message'=>'Survey berhasil dibuat.','data'=>['reload'=>true]]);
    }
    public function convert(string $id): void {
        $this->requireCsrf();if(!Auth::can('survey.convert')&&!Auth::can('quotation.create'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$db=Database::connection();$t=Auth::tenantId();$s=$db->prepare("SELECT * FROM surveys WHERE id=? AND tenant_id=? AND deleted_at IS NULL");$s->execute([(int)$id,$t]);$sv=$s->fetch();if(!$sv)Response::json(['success'=>false,'message'=>'Survey tidak ditemukan.','errors'=>[]],404);$num=NumberService::next($t,'quotation','QUO');$subtotal=(float)$sv['estimated_labor'];$tax=0;$total=$subtotal;
        $db->beginTransaction();try{$db->prepare("INSERT INTO quotations(tenant_id,quotation_number,customer_id,survey_id,quotation_date,valid_until,sales_user_id,status,subtotal,discount,tax,grand_total,terms,notes,created_at,updated_at) VALUES(?,?,?, ?,CURDATE(),DATE_ADD(CURDATE(),INTERVAL 14 DAY),?,'Draft',?,0,?,?,NULL,?,NOW(),NOW())")->execute([$t,$num,$sv['customer_id'],$sv['id'],Auth::id(),$subtotal,$tax,$total,'Generated from survey '.$sv['survey_number']]);$qid=(int)$db->lastInsertId();if($subtotal>0)$db->prepare("INSERT INTO quotation_items(tenant_id,quotation_id,item_type,description,quantity,unit,unit_price,discount,tax,line_total) VALUES(?,?,'service','Estimated labor',1,'job',?,0,0,?)")->execute([$t,$qid,$subtotal,$subtotal]);if($sv['service_request_id'])$db->prepare("UPDATE service_requests SET status='Quoted',updated_at=NOW(),updated_by=? WHERE id=? AND tenant_id=?")->execute([Auth::id(),$sv['service_request_id'],$t]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}ActivityService::log('quotation',$qid,'created_from_survey','Quotation generated from survey',['survey_id'=>(int)$sv['id']]);Response::json(['success'=>true,'message'=>'Survey dikonversi menjadi quotation '.$num.'.','data'=>['redirect'=>url('/quotations/'.$qid)]]);
    }
    private function forbidden(): void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
