<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\ActivityService;
final class TechnicianController extends Controller {
    public function skills(string $id):never{if(!Auth::can('technician.view'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$db=Database::connection();$t=(int)Auth::tenantId();$tech=$db->prepare("SELECT t.id,u.name FROM technicians t JOIN users u ON u.id=t.user_id AND u.tenant_id=t.tenant_id WHERE t.id=? AND t.tenant_id=?");$tech->execute([(int)$id,$t]);$row=$tech->fetch();if(!$row)Response::json(['success'=>false,'message'=>'Technician not found'],404);$q=$db->prepare("SELECT s.id,s.name,COALESCE(ts.level,0) level FROM skills s LEFT JOIN technician_skills ts ON ts.skill_id=s.id AND ts.tenant_id=s.tenant_id AND ts.technician_id=? WHERE s.tenant_id=? ORDER BY s.name");$q->execute([(int)$id,$t]);Response::json(['success'=>true,'data'=>['technician'=>$row,'skills'=>$q->fetchAll()]]);}
    public function setSkills(string $id):never{$this->requireCsrf();if(!Auth::can('technician.manage'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$db=Database::connection();$t=(int)Auth::tenantId();$chk=$db->prepare("SELECT id FROM technicians WHERE id=? AND tenant_id=?");$chk->execute([(int)$id,$t]);if(!$chk->fetchColumn())Response::json(['success'=>false,'message'=>'Technician not found'],404);$skills=$_POST['skills']??[];$db->beginTransaction();try{$db->prepare("DELETE FROM technician_skills WHERE tenant_id=? AND technician_id=?")->execute([$t,(int)$id]);$ins=$db->prepare("INSERT INTO technician_skills(tenant_id,technician_id,skill_id,level) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM skills WHERE tenant_id=? AND id=?)");foreach((array)$skills as $skillId=>$level){$sid=is_numeric($skillId)?(int)$skillId:(int)$level;$lvl=is_numeric($skillId)?max(1,min(5,(int)$level)):3;$ins->execute([$t,(int)$id,$sid,$lvl,$t,$sid]);}$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}Response::json(['success'=>true,'message'=>'Technician skills updated.','data'=>['reload'=>true]]);}
    public function setJobSkills(string $id):never{$this->requireCsrf();if(!Auth::can('job.assign')&&!Auth::can('dispatch.manage'))Response::json(['success'=>false,'message'=>'Forbidden'],403);$db=Database::connection();$t=(int)Auth::tenantId();$skills=array_unique(array_map('intval',(array)($_POST['skills']??[])));$db->beginTransaction();try{$db->prepare("DELETE FROM job_required_skills WHERE tenant_id=? AND job_id=?")->execute([$t,(int)$id]);$ins=$db->prepare("INSERT INTO job_required_skills(tenant_id,job_id,skill_id) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM jobs WHERE tenant_id=? AND id=? AND deleted_at IS NULL) AND EXISTS(SELECT 1 FROM skills WHERE tenant_id=? AND id=?)");foreach($skills as $sid)$ins->execute([$t,(int)$id,$sid,$t,(int)$id,$t,$sid]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}ActivityService::log('job',(int)$id,'required_skills_updated','Required technician skills updated',['skill_ids'=>$skills]);Response::json(['success'=>true,'message'=>'Required skills updated.','data'=>['reload'=>true]]);}
    public function recommend(string $id):never{if(!Auth::can('job.assign')&&!Auth::can('dispatch.view'))Response::json(['success'=>false,'message'=>'Forbidden'],403);Response::json(['success'=>true,'data'=>$this->recommendRows((int)$id)]);}
    public function recommendRows(int $jobId):array{$db=Database::connection();$t=(int)Auth::tenantId();$job=$db->prepare("SELECT j.id FROM jobs j WHERE j.id=? AND j.tenant_id=? AND j.deleted_at IS NULL");$job->execute([$jobId,$t]);if(!$job->fetch())return[];$sql="SELECT t.id technician_id,u.id user_id,u.name,t.status,t.branch_id,COUNT(DISTINCT ts.skill_id) matched_skills,(SELECT COUNT(*) FROM job_required_skills x WHERE x.tenant_id=t.tenant_id AND x.job_id=?) required_skills,(SELECT COUNT(*) FROM job_technicians jt JOIN jobs j2 ON j2.id=jt.job_id AND j2.tenant_id=jt.tenant_id WHERE jt.tenant_id=t.tenant_id AND jt.user_id=t.user_id AND j2.status NOT IN('Completed','Closed','Cancelled')) workload,COALESCE(AVG(ts.level),0) skill_level FROM technicians t JOIN users u ON u.id=t.user_id AND u.tenant_id=t.tenant_id LEFT JOIN technician_skills ts ON ts.tenant_id=t.tenant_id AND ts.technician_id=t.id AND ts.skill_id IN(SELECT skill_id FROM job_required_skills WHERE tenant_id=t.tenant_id AND job_id=?) WHERE t.tenant_id=? AND u.deleted_at IS NULL AND u.status='active' GROUP BY t.id,u.id,u.name,t.status,t.branch_id ORDER BY matched_skills DESC,(t.status='Available') DESC,workload ASC,skill_level DESC,u.name ASC LIMIT 10";$s=$db->prepare($sql);$s->execute([$jobId,$jobId,$t]);return $s->fetchAll();}
}
