<?php
namespace App\Controllers;
use App\Core\{Controller,Database,Auth,Request,Response};
use App\Services\{AuditService,SubscriptionService};
final class UserController extends Controller {
    public function index(): void {if(!Auth::can('user.view')&&!Auth::can('user.manage')){$this->forbidden();return;}$db=Database::connection();$t=Auth::tenantId();$u=$db->prepare("SELECT u.*,b.name branch_name,GROUP_CONCAT(r.name SEPARATOR ', ') roles FROM users u LEFT JOIN branches b ON b.id=u.branch_id AND b.tenant_id=u.tenant_id LEFT JOIN user_roles ur ON ur.user_id=u.id AND ur.tenant_id=u.tenant_id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.tenant_id=? AND u.deleted_at IS NULL GROUP BY u.id ORDER BY u.name");$u->execute([$t]);$r=$db->prepare("SELECT r.*,(SELECT COUNT(*) FROM role_permissions rp WHERE rp.role_id=r.id) permission_count FROM roles r WHERE r.tenant_id=? ORDER BY r.name");$r->execute([$t]);$b=$db->prepare("SELECT id,name FROM branches WHERE tenant_id=? AND deleted_at IS NULL ORDER BY name");$b->execute([$t]);$p=$db->query("SELECT * FROM permissions ORDER BY module,code")->fetchAll();$this->view('users/index',['title'=>'Users & Roles','users'=>$u->fetchAll(),'roles'=>$r->fetchAll(),'branches'=>$b->fetchAll(),'permissions'=>$p]);}
    public function create(): void {$this->requireCsrf();if(!Auth::can('user.create')&&!Auth::can('user.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$name=trim((string)Request::input('name'));$email=strtolower(trim((string)Request::input('email')));$password=(string)Request::input('password');if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8)Response::json(['success'=>false,'message'=>'Name, valid email, dan password minimal 8 karakter wajib.','errors'=>[]],422);$db=Database::connection();$t=Auth::tenantId();$limit=SubscriptionService::userLimit($t);if($limit!==null){$c=$db->prepare("SELECT COUNT(*) FROM users WHERE tenant_id=? AND deleted_at IS NULL AND status<>'inactive'");$c->execute([$t]);if((int)$c->fetchColumn()>=$limit)Response::json(['success'=>false,'message'=>'User limit subscription tercapai ('.$limit.').','errors'=>[]],422);}$db->beginTransaction();try{$db->prepare("INSERT INTO users(tenant_id,branch_id,name,email,password_hash,phone,is_platform_admin,status,created_at,updated_at) VALUES(?,?,?,?,?,?,0,'active',NOW(),NOW())")->execute([$t,Request::input('branch_id')?:null,$name,$email,password_hash($password,PASSWORD_DEFAULT),Request::input('phone')]);$uid=(int)$db->lastInsertId();$role=(int)Request::input('role_id');if($role){$v=$db->prepare("SELECT COUNT(*) FROM roles WHERE id=? AND tenant_id=?");$v->execute([$role,$t]);if($v->fetchColumn())$db->prepare("INSERT INTO user_roles(tenant_id,user_id,role_id) VALUES(?,?,?)")->execute([$t,$uid,$role]);}$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();Response::json(['success'=>false,'message'=>'Unable to create user: '.$e->getMessage(),'errors'=>[]],422);}AuditService::log('create','user',$uid,null,['email'=>$email]);Response::json(['success'=>true,'message'=>'User created.','data'=>['reload'=>true]]);}
    public function role(): void {$this->requireCsrf();if(!Auth::can('user.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$name=trim((string)Request::input('name'));$code=strtolower(preg_replace('/[^a-z0-9]+/i','_',trim((string)Request::input('code',$name))));$permissions=$_POST['permissions']??[];if($name===''||$code==='')Response::json(['success'=>false,'message'=>'Role name wajib.','errors'=>[]],422);$db=Database::connection();$t=Auth::tenantId();$db->beginTransaction();try{$db->prepare("INSERT INTO roles(tenant_id,name,code,is_system,created_at,updated_at) VALUES(?,?,?,0,NOW(),NOW())")->execute([$t,$name,$code]);$rid=(int)$db->lastInsertId();$ins=$db->prepare("INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT ?,id FROM permissions WHERE id=?");foreach($permissions as $pid)$ins->execute([$rid,(int)$pid]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();Response::json(['success'=>false,'message'=>'Unable to create role: '.$e->getMessage(),'errors'=>[]],422);}Response::json(['success'=>true,'message'=>'Custom role created.','data'=>['reload'=>true]]);}
    public function assign(string $id): void {$this->requireCsrf();if(!Auth::can('user.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$role=(int)Request::input('role_id');$db=Database::connection();$t=Auth::tenantId();$v=$db->prepare("SELECT COUNT(*) FROM roles WHERE id=? AND tenant_id=?");$v->execute([$role,$t]);if(!$v->fetchColumn())Response::json(['success'=>false,'message'=>'Role invalid.','errors'=>[]],422);$db->prepare("INSERT IGNORE INTO user_roles(tenant_id,user_id,role_id) VALUES(?,?,?)")->execute([$t,(int)$id,$role]);Response::json(['success'=>true,'message'=>'Role assigned.','data'=>['reload'=>true]]);}
    public function reset(string $id): void {$this->requireCsrf();if(!Auth::can('user.manage'))Response::json(['success'=>false,'message'=>'Forbidden','errors'=>[]],403);$password=(string)Request::input('password');if(strlen($password)<8)Response::json(['success'=>false,'message'=>'Password minimal 8 karakter.','errors'=>[]],422);Database::connection()->prepare("UPDATE users SET password_hash=?,updated_at=NOW() WHERE id=? AND tenant_id=? AND deleted_at IS NULL")->execute([password_hash($password,PASSWORD_DEFAULT),(int)$id,Auth::tenantId()]);Response::json(['success'=>true,'message'=>'Password reset.','data'=>['reload'=>true]]);}
    private function forbidden():void{http_response_code(403);require BASE_PATH.'/app/Views/errors/403.php';}
}
